import React, { createContext, useContext, useEffect, useState, type ReactNode } from 'react';

interface Translations {
  [key: string]: {
    [key: string]: string;
  };
}

const translations: Translations = {
  en: {
    home: 'Home',
    recommend: 'Recommend Crop',
    predict: 'Predict Yield',
    weatherAlerts: 'Weather',
    schemes: 'Schemes',
    tutorials: 'Tutorials',
    about: 'About Us',
    contact: 'Contact',
    title: 'FarmFusion 🌱',
    subtitle: 'Empowering farmers with AI-powered crop recommendations, yield predictions, and seamless access to government schemes.',
    btnRec: 'Get Recommendation',
    btnYield: 'Predict Yield',
    heroTitle: 'FarmFusion',
    heroSubtitle: 'Empowering farmers with AI-powered crop recommendations, yield predictions, and seamless access to government schemes for sustainable agriculture.',
    startJourney: 'Start Your Journey',
    learnMore: 'Learn More',
    heroStatFarmers: 'Farmers Helped',
    heroStatCrops: 'Crop Types',
    heroStatAccuracy: 'Accuracy',
    heroStatSchemes: 'Gov Schemes',
    cropTitle: 'Smart Crop Recommendation',
    cropSubtitle: 'Get AI-powered crop suggestions based on your soil conditions and environmental factors.',
    soilEnvData: 'Soil & Environment Data',
    recommendedCrop: 'Recommended Crop',
    optimalForConditions: 'This crop is optimal for your current soil and environmental conditions.',
    yieldTitle: 'Intelligent Yield Prediction',
    yieldSubtitle: 'Forecast your crop yields using advanced AI models based on environmental factors and farming practices.',
    cropEnvData: 'Crop & Environment Data',
    predictedYield: 'Predicted Yield',
    accuracyRate: 'Accuracy Rate',
    schemesTitle: 'Government Schemes & Support',
    schemesSubtitle: 'Explore comprehensive agricultural policies, subsidies, and support programs designed to empower farmers across India.',
    keyBenefits: 'Key Benefits',
    applyNow: 'Apply Now',
    tutorialsTitle: 'Comprehensive Learning Hub',
    tutorialsSubtitle: 'Master modern farming techniques through expert-curated tutorials, research papers, and interactive learning modules.',
    startLearning: 'Start Learning',
    learningPaths: 'Structured Learning Paths',
    aboutTitle: 'About',
    aboutSubtitle: "We're on a mission to revolutionize agriculture through artificial intelligence, making farming more efficient, sustainable, and profitable for farmers worldwide.",
    whyChoose: 'Why Choose FarmFusion?',
    ourTeam: 'Our Expert Team',
    joinRevolution: 'Join the Agricultural Revolution',
    revolutionText: "Be part of the future of farming. Together, we're building a more sustainable and prosperous agricultural ecosystem for everyone.",
    contactTitle: 'Get in Touch',
    contactSubtitle: "Have questions or need support? We're here to help you make the most of FarmFusion. Reach out to our team for personalized assistance.",
    quickMessage: 'Quick Message',
    yourName: 'Your Name',
    yourEmail: 'Your Email',
    yourMessage: 'Your Message',
    sending: 'Sending...',
    sendMessage: 'Send Message',
    faq: 'Frequently Asked Questions',
    growingTogether: 'Growing Together',
    thankYou: "Thank you for being part of the FarmFusion community. Together, we're building a smarter, more sustainable future for agriculture.",
    
    // Schemes Details
    pmKisan: 'PM-Kisan Yojana',
    pmKisanDesc: '₹6,000 annual financial support directly to small and marginal farmers.',
    pmKisanBenefit1: 'Direct benefit transfer',
    pmKisanBenefit2: 'No intermediaries',
    pmKisanBenefit3: 'Coverage across India',
    soilHealth: 'Soil Health Card',
    soilHealthDesc: 'Comprehensive soil testing and crop-specific recommendations.',
    soilHealthBenefit1: 'Free soil testing',
    soilHealthBenefit2: 'Nutrient management',
    soilHealthBenefit3: 'Yield improvement',
    pmFasal: 'PM Fasal Bima Yojana',
    pmFasalDesc: 'Comprehensive crop insurance against natural disasters and yield losses.',
    pmFasalBenefit1: 'Low premium rates',
    pmFasalBenefit2: 'Quick claim settlement',
    pmFasalBenefit3: 'Technology integration',
    kisanCredit: 'Kisan Credit Card',
    kisanCreditDesc: 'Low-interest loans for farming expenses and agricultural investments.',
    kisanCreditBenefit1: 'Easy application',
    kisanCreditBenefit2: 'Flexible repayment',
    kisanCreditBenefit3: 'Low interest rates',
    helplineSupport: 'Helpline Support',
    helplineDesc: 'Get assistance with applications and queries',
    digitalServices: 'Digital Services',
    digitalServicesDesc: 'Access services online through government portals',
    documentation: 'Documentation',
    documentationDesc: 'Required documents and eligibility criteria',
    downloadGuidelines: 'Download Guidelines',
    
    // Tutorials Details
    modernFarming: 'Modern Farming Techniques',
    modernFarmingDesc: 'Learn precision farming, smart irrigation systems, and sustainable agricultural practices.',
    cropCultivation: 'Crop Cultivation Basics',
    cropCultivationDesc: 'Comprehensive step-by-step video guide for beginners in agriculture.',
    icarResearch: 'ICAR Research Resources',
    icarResearchDesc: 'Access advanced agricultural research, publications, and expert guidance.',
    ministryGuidelines: 'Ministry Guidelines',
    ministryGuidelinesDesc: 'Official policies, latest agricultural guidelines, and government initiatives.',
    videoCourse: 'Video Course',
    videoSeries: 'Video Series',
    researchPortal: 'Research Portal',
    documentationType: 'Documentation',
    selfPaced: 'Self-paced',
    reference: 'Reference',
    beginner: 'Beginner',
    intermediate: 'Intermediate',
    advanced: 'Advanced',
    allLevels: 'All Levels',
    beginnerFarmer: 'Beginner Farmer',
    beginnerDesc: 'Start your agricultural journey',
    advancedTechniques: 'Advanced Techniques',
    advancedDesc: 'Modern farming methodologies',
    agriBusiness: 'Agri-Business',
    agriBusinessDesc: 'Commercial farming strategies',
    basicFarming: 'Basic Farming',
    soilBasics: 'Soil Basics',
    cropSelection: 'Crop Selection',
    precisionFarming: 'Precision Farming',
    iotAgriculture: 'IoT in Agriculture',
    dataAnalytics: 'Data Analytics',
    marketAnalysis: 'Market Analysis',
    supplyChain: 'Supply Chain',
    financialPlanning: 'Financial Planning',
    tutorialsCount: 'Tutorials',
    learnersCount: 'Learners',
    expertsCount: 'Experts',
    rating: 'Rating',
    
    // About Details
    ourMission: 'Our Mission',
    missionDesc: 'Empowering farmers with cutting-edge AI technology to make agriculture smarter, more sustainable, and profitable.',
    innovation: 'Innovation',
    innovationDesc: 'Bringing revolutionary AI/ML technology directly to the fields, transforming traditional farming practices.',
    community: 'Community',
    communityDesc: 'Building a strong network connecting farmers with agricultural experts, researchers, and modern resources.',
    sustainability: 'Sustainability',
    sustainabilityDesc: 'Promoting eco-friendly farming practices that protect our environment for future generations.',
    reliablePredictions: 'Reliable Predictions',
    reliableDesc: 'AI models trained on vast agricultural datasets',
    fastProcessing: 'Fast Processing',
    fastDesc: 'Instant recommendations and yield predictions',
    wideCoverage: 'Wide Coverage',
    wideDesc: 'Supporting farmers across multiple regions',
    userSatisfaction: 'User Satisfaction',
    satisfactionDesc: 'Positive feedback from farming community',
    aiTeam: 'AI Research Team',
    aiTeamRole: 'Developing advanced prediction models',
    aiExpertise: 'Machine Learning & Agriculture',
    agriExperts: 'Agricultural Experts',
    agriExpertsRole: 'Providing domain knowledge',
    agriExpertise: 'Crop Science & Soil Management',
    designTeam: 'Design Team',
    designTeamRole: 'Creating intuitive user experiences',
    designExpertise: 'UX/UI & Product Design',
    trustedFarmers: 'Trusted by 10,000+ farmers',
    uptimeGuarantee: '99.9% uptime guarantee',
    
    // Contact Details
    email: 'Email',
    phone: 'Phone',
    socialMedia: 'Social Media',
    supportHours: 'Support Hours',
    supportHoursDesc: 'Monday - Friday: 9:00 AM - 6:00 PM IST',
    location: 'Location',
    locationDesc: 'Serving farmers across India',
    responseTime: 'Response Time',
    responseTimeDesc: 'Average response within 2 hours',
    faqQ1: 'How accurate are the crop recommendations?',
    faqA1: 'Our AI models achieve 95% accuracy based on extensive testing.',
    faqQ2: 'Is FarmFusion free to use?',
    faqA2: 'Yes! Basic features are completely free for all farmers.',
    faqQ3: 'What languages do you support?',
    faqA3: 'We support English, Hindi, Tamil, Bengali, and Marathi.',
    faqQ4: 'How do I get technical support?',
    faqA4: 'Contact us via phone or email for immediate assistance.',
    nameRequired: 'Name Required',
    nameRequiredDesc: 'Please enter your name',
    invalidEmail: 'Invalid Email',
    invalidEmailDesc: 'Please enter a valid email address',
    messageRequired: 'Message Required',
    messageRequiredDesc: 'Please enter your message',
    messageSent: 'Message Sent! ✅',
    messageSentDesc: "We'll get back to you soon.",
    
    // Soil Analysis
    'soilAnalysis.title': 'AI Soil Analysis',
    'soilAnalysis.description': 'Take a photo or upload an image of your soil for instant analysis',
    'soilAnalysis.camera': 'Use Camera',
    'soilAnalysis.capture': 'Capture Photo',
    'soilAnalysis.upload': 'Upload Image',
    'soilAnalysis.getWeather': 'Get Weather Data from Location',
    'soilAnalysis.success': 'Analysis Complete!',
    'soilAnalysis.successDesc': 'Soil data has been analyzed and filled in the form.',
    'soilAnalysis.error': 'Analysis Failed',
    'soilAnalysis.cameraError': 'Camera Error',
    'soilAnalysis.cameraErrorDesc': 'Could not access camera',
    'soilAnalysis.results': 'Analysis Results',
    'soilAnalysis.soilType': 'Soil Type',
    'soilAnalysis.moisture': 'Moisture',
    'soilAnalysis.health': 'Health',
    'soilAnalysis.recommendations': 'Recommendations',
    'weather.success': 'Weather Data Retrieved!',
    'weather.successDesc': 'Environmental data has been filled in the form.',
    'weather.error': 'Location Error',
    'weather.errorDesc': 'Could not get your location',

    // Weather Alerts Section
    'weatherAlerts.title': 'Weather & Smart Planting Guide',
    'weatherAlerts.subtitle': '7-day forecast with AI-powered optimal planting time suggestions',
    'weatherAlerts.currentWeather': 'Current Weather',
    'weatherAlerts.cropProtection': 'Crop Protection Alerts',
    'weatherAlerts.temperature': 'Temperature',
    'weatherAlerts.humidity': 'Humidity',
    'weatherAlerts.rainfall': 'Rainfall (Today)',
    'weatherAlerts.forecast': '7-Day Weather Forecast',
    'weatherAlerts.plantingSuggestions': 'Optimal Planting Suggestions',
    'weatherAlerts.avgHigh': 'Avg High',
    'weatherAlerts.avgLow': 'Avg Low',
    'weatherAlerts.totalRain': 'Total Rain',
    'weatherAlerts.rainChance': 'Rain Chance',
    'weatherAlerts.bestDays': 'Best Days to Plant This Week',
    'weatherAlerts.irrigationSchedule': 'Smart Irrigation Schedule',
    'weatherAlerts.dailySchedule': 'Daily Irrigation Schedule',
    'weatherAlerts.weeklyNeeds': 'Weekly Water Needs',
    'weatherAlerts.soilMoisture': 'Soil Moisture Prediction',
    'weatherAlerts.irrigationTips': 'Irrigation Tips',
    'weatherAlerts.loading': 'Loading weather data...',
    'weatherAlerts.clickRefresh': 'Click refresh to load weather data',
    'weatherAlerts.weatherUpdated': 'Weather Updated!',
    'weatherAlerts.highTemp': 'High temperature alert! Consider irrigation and provide shade for crops.',
    'weatherAlerts.lowTemp': 'Low temperature warning! Protect crops from frost damage.',
    'weatherAlerts.highHumidity': 'High humidity detected! Risk of fungal diseases.',
    'weatherAlerts.heavyRain': 'Heavy rainfall expected! Ensure proper drainage.',
    'weatherAlerts.dryConditions': 'Dry conditions! Plan irrigation schedule.',
    'weatherAlerts.favorable': 'Weather conditions are favorable for farming.',
    
    // Yield Prediction Section
    'yield.calculating': 'Calculating Yield...',
    'yield.dataAutoFilled': 'Data Auto-Filled!',
    'yield.dataAutoFilledDesc': 'Crop data loaded. Please add pesticide and area.',
    'yield.missingInfo': 'Missing Information',
    'yield.fillAllFields': 'Please fill in all required fields.',
    'yield.predictionReady': 'Yield Prediction Ready!',
    'yield.expectedYield': 'Expected yield',
    'yield.error': 'Failed to predict yield. Please try again.',
    'yield.cropName': 'Crop Name',
    'yield.year': 'Year',
    'yield.rainfall': 'Rainfall',
    'yield.pesticide': 'Pesticide Usage',
    'yield.temperature': 'Temperature',
    'yield.area': 'Area',
    'yield.viewHistory': 'View History',
    'yield.hideHistory': 'Hide History',
    'yield.recentPredictions': 'Recent Predictions',
    'yield.deleted': 'Deleted',
    'yield.removedFromHistory': 'Prediction removed from history',
    'yield.weatherImpact': 'Weather Impact',
    'yield.weatherImpactDesc': 'Rainfall patterns affect growth cycles',
    'yield.tempImpact': 'Temperature',
    'yield.tempImpactDesc': 'Optimal temperature boosts yield',
    'yield.pesticideImpact': 'Pesticide Use',
    'yield.pesticideImpactDesc': 'Proper pest control increases output',
    'yield.areaEfficiency': 'Area Efficiency',
    'yield.areaEfficiencyDesc': 'Land utilization optimization',
    'yield.aiRecommendations': 'AI-Powered Recommendations',

    // Crop Recommendation Section
    'crop.analyzingSoil': 'Analyzing Soil...',
    'crop.recommendationGenerated': 'Recommendation Generated!',
    'crop.basedOnSoil': 'Based on your soil conditions, we recommend',
    'crop.growthDuration': 'Growth Duration',
    'crop.approximately': 'Approximately',
    'crop.days': 'days',
    'crop.useForYield': 'Use for Yield Prediction',
    'crop.marketInsights': 'Market Price Insights',
    'crop.currentPrice': 'Current Price',
    'crop.avgPrice': 'Avg Price (12mo)',
    'crop.bestSellTime': 'Best Sell Time',
    'crop.priceHistory': '12-Month Price Trend',
    'crop.recommendation': 'Recommendation',
    'crop.soilAnalysis': 'Soil Analysis',
    'crop.soilAnalysisDesc': 'NPK levels determine nutrient availability',
    'crop.climateFactors': 'Climate Factors',
    'crop.climateFactorsDesc': 'Temperature and humidity affect growth',
    'crop.waterManagement': 'Water Management',
    'crop.waterManagementDesc': 'Rainfall patterns guide irrigation needs',
    'crop.phBalance': 'pH Balance',
    'crop.phBalanceDesc': 'Optimal pH ensures nutrient uptake',
    'crop.nitrogen': 'Nitrogen (N)',
    'crop.phosphorus': 'Phosphorus (P)',
    'crop.potassium': 'Potassium (K)',
    'crop.humidity': 'Humidity',
    'crop.phValue': 'pH Value',

    // Chatbot
    'chatbot.title': 'Adiii - Farm Assistant',
    'chatbot.placeholder': 'Ask Adiii about farming...',
    'chatbot.listening': 'Listening...',
    'chatbot.speakNow': 'Speak now',
    'chatbot.greeting': "Hi! I'm Adiii",
    'chatbot.askAnything': 'Ask me anything about farming!',
    'chatbot.topics': 'Crops • Weather • Pests • Soil • Techniques',
    'chatbot.voiceSupport': 'Speak or type in 5 languages',
    'chatbot.language': 'Language',
    'chatbot.stop': 'Stop',

    // Navigation Auth
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.loginSignup': 'Login / Sign Up',
    'nav.welcome': 'Welcome',
    'nav.hello': 'Hello',

    // Crop Recommendation additional
    'crop.yourLocation': 'Your Location',
    'crop.forMarketPrices': 'for market prices',
    'crop.locationPlaceholder': 'e.g. Pune, Maharashtra',
    'crop.useCurrentLocation': 'Use current location',
    'crop.geolocationNotSupported': 'Geolocation not supported',
    'crop.couldNotGetLocation': 'Could not get location',
    'crop.locationRequired': 'Location Required',
    'crop.locationRequiredDesc': 'Please enter your location to find nearby markets with prices.',
    'crop.nearbyMarkets': 'Nearby Markets & Buyers',
    'crop.findingMarkets': 'Finding best markets near you...',
    'crop.avgPriceShort': 'Avg Price',
    'crop.transport': 'Transport',
    'crop.error': 'Error',
    'crop.errorDesc': 'Failed to generate recommendation. Please try again.',
    'crop.marketsUnavailable': 'Markets unavailable',
    'crop.couldNotFetchMarkets': 'Could not fetch markets',
    'cropName.Rice': 'Rice',
    'cropName.Wheat': 'Wheat',
    'cropName.Corn': 'Corn',
    'cropName.Barley': 'Barley',
    'cropName.Sugarcane': 'Sugarcane',
    'cropName.Cotton': 'Cotton',
    'cropName.Tomato': 'Tomato',
    'cropName.Potato': 'Potato',
    'crop.months': 'months',
    'crop.trendUp': 'Rising',
    'crop.trendDown': 'Falling',
    'crop.trendStable': 'Stable',
    'crop.pricesAboveAvg': 'Prices are above average. Consider selling soon or wait for peak months.',
    'crop.pricesBelowAvg': 'Prices are below average. Best to store and sell during peak months.',
    'crop.pricesStable': 'Stable prices. Sell during peak months for best returns.',
    'crop.perQuintal': '/quintal',
  },
  hi: {
    home: 'होम',
    recommend: 'फसल सुझाव',
    predict: 'उपज पूर्वानुमान',
    weatherAlerts: 'मौसम',
    schemes: 'योजनाएँ',
    tutorials: 'ट्यूटोरियल',
    about: 'हमारे बारे में',
    contact: 'संपर्क',
    title: 'फार्मफ्यूजन 🌱',
    subtitle: 'किसानों की मदद AI से फसल सुझाव, उपज पूर्वानुमान और सरकारी योजनाओं तक पहुंच से।',
    btnRec: 'सुझाव प्राप्त करें',
    btnYield: 'उपज अनुमान',
    heroTitle: 'फार्मफ्यूजन',
    heroSubtitle: 'किसानों को AI-संचालित फसल सिफारिशों, उपज पूर्वानुमान, और टिकाऊ कृषि के लिए सरकारी योजनाओं तक निर्बाध पहुंच के साथ सशक्त बनाना।',
    startJourney: 'अपनी यात्रा शुरू करें',
    learnMore: 'और जानें',
    heroStatFarmers: 'मदद किए किसान',
    heroStatCrops: 'फसल प्रकार',
    heroStatAccuracy: 'सटीकता',
    heroStatSchemes: 'सरकारी योजनाएँ',
    cropTitle: 'स्मार्ट फसल सुझाव',
    cropSubtitle: 'अपनी मिट्टी की स्थिति और पर्यावरणीय कारकों के आधार पर AI-संचालित फसल सुझाव पाएं।',
    soilEnvData: 'मिट्टी और पर्यावरण डेटा',
    recommendedCrop: 'सुझाई गई फसल',
    optimalForConditions: 'यह फसल आपकी वर्तमान मिट्टी और पर्यावरणीय परिस्थितियों के लिए उपयुक्त है।',
    yieldTitle: 'स्मार्ट उपज पूर्वानुमान',
    yieldSubtitle: 'पर्यावरणीय कारकों और खेती के तरीकों के आधार पर उन्नत AI मॉडलों से अपनी फसल की उपज का पूर्वानुमान लगाएं।',
    cropEnvData: 'फसल और पर्यावरण डेटा',
    predictedYield: 'अनुमानित उपज',
    accuracyRate: 'सटीकता दर',
    schemesTitle: 'सरकारी योजनाएं और सहायता',
    schemesSubtitle: 'भारत भर के किसानों को सशक्त बनाने के लिए डिज़ाइन की गई व्यापक कृषि नीतियां, सब्सिडी और सहायता कार्यक्रम देखें।',
    keyBenefits: 'मुख्य लाभ',
    applyNow: 'अभी आवेदन करें',
    tutorialsTitle: 'व्यापक शिक्षण केंद्र',
    tutorialsSubtitle: 'विशेषज्ञ-क्यूरेटेड ट्यूटोरियल, शोध पत्र और इंटरैक्टिव शिक्षण मॉड्यूल के माध्यम से आधुनिक कृषि तकनीकों में महारत हासिल करें।',
    startLearning: 'सीखना शुरू करें',
    learningPaths: 'संरचित सीखने के रास्ते',
    aboutTitle: 'के बारे में',
    aboutSubtitle: 'हम कृत्रिम बुद्धिमत्ता के माध्यम से कृषि में क्रांति लाने के मिशन पर हैं, जिससे दुनिया भर के किसानों के लिए खेती अधिक कुशल, टिकाऊ और लाभदायक हो।',
    whyChoose: 'फार्मफ्यूजन क्यों चुनें?',
    ourTeam: 'हमारी विशेषज्ञ टीम',
    joinRevolution: 'कृषि क्रांति में शामिल हों',
    revolutionText: 'खेती के भविष्य का हिस्सा बनें। साथ मिलकर, हम सभी के लिए एक अधिक टिकाऊ और समृद्ध कृषि पारिस्थितिकी तंत्र बना रहे हैं।',
    contactTitle: 'संपर्क में रहें',
    contactSubtitle: 'प्रश्न हैं या सहायता चाहिए? हम यहां आपको फार्मफ्यूजन का अधिकतम लाभ उठाने में मदद करने के लिए हैं। व्यक्तिगत सहायता के लिए हमारी टीम से संपर्क करें।',
    quickMessage: 'त्वरित संदेश',
    yourName: 'आपका नाम',
    yourEmail: 'आपका ईमेल',
    yourMessage: 'आपका संदेश',
    sending: 'भेजा जा रहा है...',
    sendMessage: 'संदेश भेजें',
    faq: 'अक्सर पूछे जाने वाले प्रश्न',
    growingTogether: 'साथ मिलकर बढ़ना',
    thankYou: 'फार्मफ्यूजन समुदाय का हिस्सा बनने के लिए धन्यवाद। साथ मिलकर, हम कृषि के लिए एक स्मार्ट, अधिक टिकाऊ भविष्य बना रहे हैं।',
    
    pmKisan: 'पीएम-किसान योजना',
    pmKisanDesc: '₹6,000 वार्षिक वित्तीय सहायता सीधे छोटे और सीमांत किसानों को।',
    pmKisanBenefit1: 'प्रत्यक्ष लाभ हस्तांतरण',
    pmKisanBenefit2: 'कोई बिचौलिए नहीं',
    pmKisanBenefit3: 'पूरे भारत में कवरेज',
    soilHealth: 'मृदा स्वास्थ्य कार्ड',
    soilHealthDesc: 'व्यापक मिट्टी परीक्षण और फसल-विशिष्ट सिफारिशें।',
    soilHealthBenefit1: 'मुफ्त मिट्टी परीक्षण',
    soilHealthBenefit2: 'पोषक तत्व प्रबंधन',
    soilHealthBenefit3: 'उपज में सुधार',
    pmFasal: 'पीएम फसल बीमा योजना',
    pmFasalDesc: 'प्राकृतिक आपदाओं और उपज नुकसान के खिलाफ व्यापक फसल बीमा।',
    pmFasalBenefit1: 'कम प्रीमियम दरें',
    pmFasalBenefit2: 'त्वरित दावा निपटान',
    pmFasalBenefit3: 'प्रौद्योगिकी एकीकरण',
    kisanCredit: 'किसान क्रेडिट कार्ड',
    kisanCreditDesc: 'कृषि खर्चों और निवेश के लिए कम ब्याज ऋण।',
    kisanCreditBenefit1: 'आसान आवेदन',
    kisanCreditBenefit2: 'लचीली चुकौती',
    kisanCreditBenefit3: 'कम ब्याज दरें',
    helplineSupport: 'हेल्पलाइन सहायता',
    helplineDesc: 'आवेदन और प्रश्नों में सहायता प्राप्त करें',
    digitalServices: 'डिजिटल सेवाएं',
    digitalServicesDesc: 'सरकारी पोर्टल के माध्यम से ऑनलाइन सेवाओं तक पहुंचें',
    documentation: 'प्रलेखन',
    documentationDesc: 'आवश्यक दस्तावेज और पात्रता मानदंड',
    downloadGuidelines: 'दिशानिर्देश डाउनलोड करें',
    
    modernFarming: 'आधुनिक कृषि तकनीक',
    modernFarmingDesc: 'सटीक खेती, स्मार्ट सिंचाई प्रणाली और टिकाऊ कृषि प्रथाओं को सीखें।',
    cropCultivation: 'फसल खेती मूल बातें',
    cropCultivationDesc: 'कृषि में शुरुआती लोगों के लिए व्यापक चरण-दर-चरण वीडियो गाइड।',
    icarResearch: 'ICAR शोध संसाधन',
    icarResearchDesc: 'उन्नत कृषि अनुसंधान, प्रकाशनों और विशेषज्ञ मार्गदर्शन तक पहुंचें।',
    ministryGuidelines: 'मंत्रालय दिशानिर्देश',
    ministryGuidelinesDesc: 'आधिकारिक नीतियां, नवीनतम कृषि दिशानिर्देश और सरकारी पहल।',
    videoCourse: 'वीडियो कोर्स',
    videoSeries: 'वीडियो श्रृंखला',
    researchPortal: 'शोध पोर्टल',
    documentationType: 'प्रलेखन',
    selfPaced: 'स्व-गति',
    reference: 'संदर्भ',
    beginner: 'शुरुआती',
    intermediate: 'मध्यवर्ती',
    advanced: 'उन्नत',
    allLevels: 'सभी स्तर',
    beginnerFarmer: 'शुरुआती किसान',
    beginnerDesc: 'अपनी कृषि यात्रा शुरू करें',
    advancedTechniques: 'उन्नत तकनीक',
    advancedDesc: 'आधुनिक कृषि पद्धतियां',
    agriBusiness: 'कृषि व्यवसाय',
    agriBusinessDesc: 'वाणिज्यिक कृषि रणनीतियां',
    basicFarming: 'बुनियादी खेती',
    soilBasics: 'मिट्टी की मूल बातें',
    cropSelection: 'फसल चयन',
    precisionFarming: 'सटीक खेती',
    iotAgriculture: 'कृषि में IoT',
    dataAnalytics: 'डेटा एनालिटिक्स',
    marketAnalysis: 'बाजार विश्लेषण',
    supplyChain: 'आपूर्ति श्रृंखला',
    financialPlanning: 'वित्तीय योजना',
    tutorialsCount: 'ट्यूटोरियल',
    learnersCount: 'शिक्षार्थी',
    expertsCount: 'विशेषज्ञ',
    rating: 'रेटिंग',
    
    ourMission: 'हमारा मिशन',
    missionDesc: 'कृषि को अधिक स्मार्ट, टिकाऊ और लाभदायक बनाने के लिए अत्याधुनिक AI तकनीक से किसानों को सशक्त बनाना।',
    innovation: 'नवाचार',
    innovationDesc: 'पारंपरिक कृषि प्रथाओं को बदलते हुए AI/ML तकनीक को सीधे खेतों में लाना।',
    community: 'समुदाय',
    communityDesc: 'कृषि विशेषज्ञों, शोधकर्ताओं और आधुनिक संसाधनों के साथ किसानों को जोड़ने वाला एक मजबूत नेटवर्क बनाना।',
    sustainability: 'स्थिरता',
    sustainabilityDesc: 'पर्यावरण के अनुकूल कृषि प्रथाओं को बढ़ावा देना जो आने वाली पीढ़ियों के लिए हमारे पर्यावरण की रक्षा करती हैं।',
    reliablePredictions: 'विश्वसनीय पूर्वानुमान',
    reliableDesc: 'विशाल कृषि डेटासेट पर प्रशिक्षित AI मॉडल',
    fastProcessing: 'तेज प्रसंस्करण',
    fastDesc: 'तत्काल सिफारिशें और उपज पूर्वानुमान',
    wideCoverage: 'व्यापक कवरेज',
    wideDesc: 'कई क्षेत्रों में किसानों को समर्थन',
    userSatisfaction: 'उपयोगकर्ता संतुष्टि',
    satisfactionDesc: 'कृषक समुदाय से सकारात्मक प्रतिक्रिया',
    aiTeam: 'AI अनुसंधान टीम',
    aiTeamRole: 'उन्नत पूर्वानुमान मॉडल विकसित करना',
    aiExpertise: 'मशीन लर्निंग और कृषि',
    agriExperts: 'कृषि विशेषज्ञ',
    agriExpertsRole: 'डोमेन ज्ञान प्रदान करना',
    agriExpertise: 'फसल विज्ञान और मृदा प्रबंधन',
    designTeam: 'डिजाइन टीम',
    designTeamRole: 'सहज उपयोगकर्ता अनुभव बनाना',
    designExpertise: 'UX/UI और उत्पाद डिजाइन',
    trustedFarmers: '10,000+ किसानों द्वारा भरोसा',
    uptimeGuarantee: '99.9% अपटाइम गारंटी',
    
    email: 'ईमेल',
    phone: 'फोन',
    socialMedia: 'सोशल मीडिया',
    supportHours: 'सहायता घंटे',
    supportHoursDesc: 'सोमवार - शुक्रवार: सुबह 9:00 - शाम 6:00 IST',
    location: 'स्थान',
    locationDesc: 'पूरे भारत में किसानों की सेवा',
    responseTime: 'प्रतिक्रिया समय',
    responseTimeDesc: '2 घंटे के भीतर औसत प्रतिक्रिया',
    faqQ1: 'फसल सिफारिशें कितनी सटीक हैं?',
    faqA1: 'व्यापक परीक्षण के आधार पर हमारे AI मॉडल 95% सटीकता प्राप्त करते हैं।',
    faqQ2: 'क्या FarmFusion उपयोग करने के लिए मुफ्त है?',
    faqA2: 'हां! सभी किसानों के लिए बुनियादी सुविधाएं पूरी तरह से मुफ्त हैं।',
    faqQ3: 'आप कौन सी भाषाओं का समर्थन करते हैं?',
    faqA3: 'हम अंग्रेजी, हिंदी, तमिल, बंगाली और मराठी का समर्थन करते हैं।',
    faqQ4: 'मैं तकनीकी सहायता कैसे प्राप्त करूं?',
    faqA4: 'तत्काल सहायता के लिए हमें फोन या ईमेल के माध्यम से संपर्क करें।',
    nameRequired: 'नाम आवश्यक है',
    nameRequiredDesc: 'कृपया अपना नाम दर्ज करें',
    invalidEmail: 'अमान्य ईमेल',
    invalidEmailDesc: 'कृपया एक मान्य ईमेल पता दर्ज करें',
    messageRequired: 'संदेश आवश्यक है',
    messageRequiredDesc: 'कृपया अपना संदेश दर्ज करें',
    messageSent: 'संदेश भेजा गया! ✅',
    messageSentDesc: 'हम जल्द ही आपसे संपर्क करेंगे।',
    
    // Soil Analysis
    'soilAnalysis.title': 'एआई मिट्टी विश्लेषण',
    'soilAnalysis.description': 'तुरंत विश्लेषण के लिए अपनी मिट्टी की फोटो लें या छवि अपलोड करें',
    'soilAnalysis.camera': 'कैमरा उपयोग करें',
    'soilAnalysis.capture': 'फोटो लें',
    'soilAnalysis.upload': 'छवि अपलोड करें',
    'soilAnalysis.getWeather': 'स्थान से मौसम डेटा प्राप्त करें',
    'soilAnalysis.success': 'विश्लेषण पूर्ण!',
    'soilAnalysis.successDesc': 'मिट्टी के डेटा का विश्लेषण किया गया है और फॉर्म में भरा गया है।',
    'soilAnalysis.error': 'विश्लेषण विफल',
    'soilAnalysis.cameraError': 'कैमरा त्रुटि',
    'soilAnalysis.cameraErrorDesc': 'कैमरा एक्सेस नहीं कर सके',
    'soilAnalysis.results': 'विश्लेषण परिणाम',
    'soilAnalysis.soilType': 'मिट्टी का प्रकार',
    'soilAnalysis.moisture': 'नमी',
    'soilAnalysis.health': 'स्वास्थ्य',
    'soilAnalysis.recommendations': 'सिफारिशें',
    'weather.success': 'मौसम डेटा प्राप्त किया गया!',
    'weather.successDesc': 'पर्यावरणीय डेटा फॉर्म में भरा गया है।',
    'weather.error': 'स्थान त्रुटि',
    'weather.errorDesc': 'आपका स्थान प्राप्त नहीं कर सके',

    // Weather Alerts Section
    'weatherAlerts.title': 'मौसम और स्मार्ट रोपण गाइड',
    'weatherAlerts.subtitle': 'AI-संचालित इष्टतम रोपण समय सुझावों के साथ 7-दिन का पूर्वानुमान',
    'weatherAlerts.currentWeather': 'वर्तमान मौसम',
    'weatherAlerts.cropProtection': 'फसल सुरक्षा अलर्ट',
    'weatherAlerts.temperature': 'तापमान',
    'weatherAlerts.humidity': 'आर्द्रता',
    'weatherAlerts.rainfall': 'वर्षा (आज)',
    'weatherAlerts.forecast': '7-दिन मौसम पूर्वानुमान',
    'weatherAlerts.plantingSuggestions': 'इष्टतम रोपण सुझाव',
    'weatherAlerts.avgHigh': 'औसत उच्च',
    'weatherAlerts.avgLow': 'औसत न्यून',
    'weatherAlerts.totalRain': 'कुल वर्षा',
    'weatherAlerts.rainChance': 'वर्षा संभावना',
    'weatherAlerts.bestDays': 'इस सप्ताह रोपण के लिए सर्वोत्तम दिन',
    'weatherAlerts.irrigationSchedule': 'स्मार्ट सिंचाई अनुसूची',
    'weatherAlerts.dailySchedule': 'दैनिक सिंचाई अनुसूची',
    'weatherAlerts.weeklyNeeds': 'साप्ताहिक पानी की आवश्यकता',
    'weatherAlerts.soilMoisture': 'मिट्टी नमी पूर्वानुमान',
    'weatherAlerts.irrigationTips': 'सिंचाई सुझाव',
    'weatherAlerts.loading': 'मौसम डेटा लोड हो रहा है...',
    'weatherAlerts.clickRefresh': 'मौसम डेटा लोड करने के लिए रीफ्रेश क्लिक करें',
    'weatherAlerts.weatherUpdated': 'मौसम अपडेट किया गया!',
    'weatherAlerts.highTemp': 'उच्च तापमान अलर्ट! सिंचाई पर विचार करें और फसलों को छाया दें।',
    'weatherAlerts.lowTemp': 'कम तापमान चेतावनी! फसलों को पाले से बचाएं।',
    'weatherAlerts.highHumidity': 'उच्च आर्द्रता! फफूंद रोगों का खतरा।',
    'weatherAlerts.heavyRain': 'भारी वर्षा अपेक्षित! जल निकासी सुनिश्चित करें।',
    'weatherAlerts.dryConditions': 'शुष्क परिस्थितियां! सिंचाई की योजना बनाएं।',
    'weatherAlerts.favorable': 'मौसम की स्थिति खेती के लिए अनुकूल है।',
    
    // Yield Prediction Section
    'yield.calculating': 'उपज की गणना हो रही है...',
    'yield.dataAutoFilled': 'डेटा स्वतः भरा गया!',
    'yield.dataAutoFilledDesc': 'फसल डेटा लोड किया गया। कृपया कीटनाशक और क्षेत्र जोड़ें।',
    'yield.missingInfo': 'जानकारी अधूरी है',
    'yield.fillAllFields': 'कृपया सभी आवश्यक फ़ील्ड भरें।',
    'yield.predictionReady': 'उपज पूर्वानुमान तैयार!',
    'yield.expectedYield': 'अपेक्षित उपज',
    'yield.error': 'उपज पूर्वानुमान विफल। कृपया पुनः प्रयास करें।',
    'yield.cropName': 'फसल का नाम',
    'yield.year': 'वर्ष',
    'yield.rainfall': 'वर्षा',
    'yield.pesticide': 'कीटनाशक उपयोग',
    'yield.temperature': 'तापमान',
    'yield.area': 'क्षेत्र',
    'yield.viewHistory': 'इतिहास देखें',
    'yield.hideHistory': 'इतिहास छुपाएं',
    'yield.recentPredictions': 'हाल के पूर्वानुमान',
    'yield.deleted': 'हटाया गया',
    'yield.removedFromHistory': 'पूर्वानुमान इतिहास से हटाया गया',
    'yield.weatherImpact': 'मौसम प्रभाव',
    'yield.weatherImpactDesc': 'वर्षा पैटर्न विकास चक्र को प्रभावित करते हैं',
    'yield.tempImpact': 'तापमान',
    'yield.tempImpactDesc': 'इष्टतम तापमान उपज बढ़ाता है',
    'yield.pesticideImpact': 'कीटनाशक उपयोग',
    'yield.pesticideImpactDesc': 'उचित कीट नियंत्रण उत्पादन बढ़ाता है',
    'yield.areaEfficiency': 'क्षेत्र दक्षता',
    'yield.areaEfficiencyDesc': 'भूमि उपयोग अनुकूलन',
    'yield.aiRecommendations': 'AI-संचालित सिफारिशें',

    // Crop Recommendation Section
    'crop.analyzingSoil': 'मिट्टी का विश्लेषण हो रहा है...',
    'crop.recommendationGenerated': 'सिफारिश तैयार!',
    'crop.basedOnSoil': 'आपकी मिट्टी की स्थिति के आधार पर, हम सुझाव देते हैं',
    'crop.growthDuration': 'विकास अवधि',
    'crop.approximately': 'लगभग',
    'crop.days': 'दिन',
    'crop.useForYield': 'उपज पूर्वानुमान के लिए उपयोग करें',
    'crop.marketInsights': 'बाजार मूल्य अंतर्दृष्टि',
    'crop.currentPrice': 'वर्तमान मूल्य',
    'crop.avgPrice': 'औसत मूल्य (12 माह)',
    'crop.bestSellTime': 'बेचने का सर्वोत्तम समय',
    'crop.priceHistory': '12-महीने मूल्य रुझान',
    'crop.recommendation': 'सिफारिश',
    'crop.soilAnalysis': 'मिट्टी विश्लेषण',
    'crop.soilAnalysisDesc': 'NPK स्तर पोषक तत्वों की उपलब्धता निर्धारित करते हैं',
    'crop.climateFactors': 'जलवायु कारक',
    'crop.climateFactorsDesc': 'तापमान और आर्द्रता विकास को प्रभावित करते हैं',
    'crop.waterManagement': 'जल प्रबंधन',
    'crop.waterManagementDesc': 'वर्षा पैटर्न सिंचाई आवश्यकताओं का मार्गदर्शन करते हैं',
    'crop.phBalance': 'pH संतुलन',
    'crop.phBalanceDesc': 'इष्टतम pH पोषक तत्व अवशोषण सुनिश्चित करता है',
    'crop.nitrogen': 'नाइट्रोजन (N)',
    'crop.phosphorus': 'फास्फोरस (P)',
    'crop.potassium': 'पोटैशियम (K)',
    'crop.humidity': 'आर्द्रता',
    'crop.phValue': 'pH मान',

    // Chatbot
    'chatbot.title': 'नेत्या - कृषि सहायक',
    'chatbot.placeholder': 'नेत्या से खेती के बारे में पूछें...',
    'chatbot.listening': 'सुन रहा है...',
    'chatbot.speakNow': 'अभी बोलें',
    'chatbot.greeting': 'नमस्ते! मैं नेत्या हूं',
    'chatbot.askAnything': 'खेती के बारे में कुछ भी पूछें!',
    'chatbot.topics': 'फसलें • मौसम • कीट • मिट्टी • तकनीक',
    'chatbot.voiceSupport': '5 भाषाओं में बोलें या टाइप करें',
    'chatbot.language': 'भाषा',
    'chatbot.stop': 'रोकें',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉगआउट',
    'nav.loginSignup': 'लॉगिन / साइन अप',
    'nav.welcome': 'स्वागत',
    'nav.hello': 'नमस्ते',
    'crop.yourLocation': 'आपका स्थान',
    'crop.forMarketPrices': 'बाजार मूल्यों के लिए',
    'crop.locationPlaceholder': 'जैसे पुणे, महाराष्ट्र',
    'crop.useCurrentLocation': 'वर्तमान स्थान उपयोग करें',
    'crop.geolocationNotSupported': 'जियोलोकेशन समर्थित नहीं है',
    'crop.couldNotGetLocation': 'स्थान प्राप्त नहीं हो सका',
    'crop.locationRequired': 'स्थान आवश्यक है',
    'crop.locationRequiredDesc': 'कृपया निकटतम बाजार खोजने के लिए अपना स्थान दर्ज करें।',
    'crop.nearbyMarkets': 'निकटतम बाजार और खरीदार',
    'crop.findingMarkets': 'आपके पास सर्वोत्तम बाजार खोज रहे हैं...',
    'crop.avgPriceShort': 'औसत मूल्य',
    'crop.transport': 'परिवहन',
    'crop.error': 'त्रुटि',
    'crop.errorDesc': 'सिफारिश उत्पन्न करने में विफल। कृपया पुनः प्रयास करें।',
    'crop.marketsUnavailable': 'बाजार उपलब्ध नहीं',
    'crop.couldNotFetchMarkets': 'बाजार प्राप्त नहीं हो सके',
    'cropName.Rice': 'चावल',
    'cropName.Wheat': 'गेहूं',
    'cropName.Corn': 'मक्का',
    'cropName.Barley': 'जौ',
    'cropName.Sugarcane': 'गन्ना',
    'cropName.Cotton': 'कपास',
    'cropName.Tomato': 'टमाटर',
    'cropName.Potato': 'आलू',
    'crop.months': 'महीने',
    'crop.trendUp': 'बढ़ रहा है',
    'crop.trendDown': 'गिर रहा है',
    'crop.trendStable': 'स्थिर',
    'crop.pricesAboveAvg': 'कीमतें औसत से ऊपर हैं। जल्द बेचने पर विचार करें या चरम महीनों तक प्रतीक्षा करें।',
    'crop.pricesBelowAvg': 'कीमतें औसत से नीचे हैं। चरम महीनों में भंडारित करके बेचना सबसे अच्छा है।',
    'crop.pricesStable': 'स्थिर कीमतें। सर्वोत्तम रिटर्न के लिए चरम महीनों में बेचें।',
    'crop.perQuintal': '/क्विंटल',
  },
  ta: {
    home: 'முகப்பு',
    recommend: 'பயிர் பரிந்துரை',
    predict: 'விளைச்சல் கணிப்பு',
    weatherAlerts: 'வானிலை',
    schemes: 'திட்டங்கள்',
    tutorials: 'பயிற்சிகள்',
    about: 'எங்களை பற்றி',
    contact: 'தொடர்பு',
    title: 'ஃபார்ம் ஃப்யூஷன் 🌱',
    subtitle: 'விவசாயிகளை AI மூலம் பயிர் பரிந்துரைகள் மற்றும் அரசு திட்டங்களுடன் உதவுதல்.',
    btnRec: 'பரிந்துரை பெறுக',
    btnYield: 'விளைச்சல் கணிக்க',
    heroTitle: 'ஃபார்ம் ஃப்யூஷன்',
    heroSubtitle: 'நிலையான விவசாயத்திற்கான AI-இயக்கப்படும் பயிர் பரிந்துரைகள், விளைச்சல் கணிப்புகள் மற்றும் அரசாங்க திட்டங்களுக்கான தடையற்ற அணுகலுடன் விவசாயிகளை வலுப்படுத்துதல்.',
    startJourney: 'உங்கள் பயணத்தைத் தொடங்குங்கள்',
    learnMore: 'மேலும் அறிக',
    heroStatFarmers: 'உதவிய விவசாயிகள்',
    heroStatCrops: 'பயிர் வகைகள்',
    heroStatAccuracy: 'துல்லியம்',
    heroStatSchemes: 'அரசுத் திட்டங்கள்',
    cropTitle: 'ஸ்மார்ட் பயிர் பரிந்துரை',
    cropSubtitle: 'உங்கள் மண் மற்றும் சுற்றுப்புற நிலைமைகளை அடிப்படையாகக் கொண்டு AI மூலம் பயிர் பரிந்துரைகளை பெறுங்கள்.',
    soilEnvData: 'மண் மற்றும் சுற்றுப்புறத் தரவு',
    recommendedCrop: 'பரிந்துரைக்கப்பட்ட பயிர்',
    optimalForConditions: 'இந்த பயிர் உங்கள் தற்போதைய மண் மற்றும் சுற்றுப்புற சூழல்களுக்கு சிறந்தது.',
    yieldTitle: 'புத்திசாலி விளைச்சல் கணிப்பு',
    yieldSubtitle: 'சுற்றுப்புற காரணிகள் மற்றும் விவசாய நடைமுறைகளை அடிப்படையாகக் கொண்டு மேம்பட்ட AI மாதிரிகள் மூலம் விளைச்சலை முன்னறியுங்கள்.',
    cropEnvData: 'பயிர் மற்றும் சுற்றுப்புறத் தரவு',
    predictedYield: 'முன்னறியப்பட்ட விளைச்சல்',
    accuracyRate: 'துல்லிய விகிதம்',
    schemesTitle: 'அரசாங்கத் திட்டங்கள் மற்றும் ஆதரவு',
    schemesSubtitle: 'இந்தியா முழுவதும் விவசாயிகளை வலுப்படுத்த வடிவமைக்கப்பட்ட விரிவான விவசாயக் கொள்கைகள், மானியங்கள் மற்றும் ஆதரவு திட்டங்களை ஆராயுங்கள்.',
    keyBenefits: 'முக்கிய நன்மைகள்',
    applyNow: 'இப்போது விண்ணப்பிக்கவும்',
    tutorialsTitle: 'விரிவான கற்றல் மையம்',
    tutorialsSubtitle: 'நிபுணர் தேர்ந்தெடுத்த பயிற்சிகள், ஆராய்ச்சி ஆவணங்கள் மற்றும் ஊடாடும் கற்றல் தொகுதிகள் மூலம் நவீன விவசாய நுட்பங்களில் தேர்ச்சி பெறுங்கள்.',
    startLearning: 'கற்றல் தொடங்குங்கள்',
    learningPaths: 'கட்டமைக்கப்பட்ட கற்றல் பாதைகள்',
    aboutTitle: 'பற்றி',
    aboutSubtitle: 'செயற்கை நுண்ணறிவு மூலம் விவசாயத்தில் புரட்சி செய்யும் பணியில் நாங்கள் ஈடுபட்டுள்ளோம், உலகம் முழுவதும் உள்ள விவசாயிகளுக்கு விவசாயத்தை மிகவும் திறமையானதாகவும், நிலையானதாகவும் மற்றும் லாபகரமானதாகவும் மாற்றுகிறோம்.',
    whyChoose: 'ஃபார்ம் ஃப்யூஷனை ஏன் தேர்வு செய்ய வேண்டும்?',
    ourTeam: 'எங்கள் நிபுணர் குழு',
    joinRevolution: 'விவசாயப் புரட்சியில் சேருங்கள்',
    revolutionText: 'விவசாயத்தின் எதிர்காலத்தின் ஒரு பகுதியாக இருங்கள். ஒன்றாக, அனைவருக்கும் மிகவும் நிலையான மற்றும் செழிப்பான விவசாய சுற்றுச்சூழல் அமைப்பை நாங்கள் கட்டமைக்கிறோம்.',
    contactTitle: 'தொடர்பில் இருங்கள்',
    contactSubtitle: 'கேள்விகள் உள்ளதா அல்லது ஆதரவு தேவையா? ஃபார்ம் ஃப்யூஷனை அதிகபட்சமாக பயன்படுத்த உங்களுக்கு உதவ நாங்கள் இங்கே இருக்கிறோம். தனிப்பயனாக்கப்பட்ட உதவிக்கு எங்கள் குழுவை தொடர்பு கொள்ளவும்.',
    quickMessage: 'விரைவு செய்தி',
    yourName: 'உங்கள் பெயர்',
    yourEmail: 'உங்கள் மின்னஞ்சல்',
    yourMessage: 'உங்கள் செய்தி',
    sending: 'அனுப்புகிறது...',
    sendMessage: 'செய்தி அனுப்பவும்',
    faq: 'அடிக்கடி கேட்கப்படும் கேள்விகள்',
    growingTogether: 'ஒன்றாக வளர்தல்',
    thankYou: 'ஃபார்ம் ஃப்யூஷன் சமூகத்தின் ஒரு பகுதியாக இருப்பதற்கு நன்றி. ஒன்றாக, விவசாயத்திற்கு ஒரு புத்திசாலித்தனமான, மிகவும் நிலையான எதிர்காலத்தை நாங்கள் உருவாக்குகிறோம்.',
    
    pmKisan: 'பிரதமர் கிசான் யோஜனா',
    pmKisanDesc: '₹6,000 ஆண்டு நிதி உதவி சிறு மற்றும் குறுகிய விவசாயிகளுக்கு நேரடியாக.',
    pmKisanBenefit1: 'நேரடி பலன் பரிமாற்றம்',
    pmKisanBenefit2: 'இடைத்தரகர்கள் இல்லை',
    pmKisanBenefit3: 'இந்தியா முழுவதும் கவரேஜ்',
    soilHealth: 'மண் சுகாதார அட்டை',
    soilHealthDesc: 'விரிவான மண் சோதனை மற்றும் பயிர்-குறிப்பிட்ட பரிந்துரைகள்.',
    soilHealthBenefit1: 'இலவச மண் சோதனை',
    soilHealthBenefit2: 'ஊட்டச்சத்து மேலாண்மை',
    soilHealthBenefit3: 'விளைச்சல் முன்னேற்றம்',
    pmFasal: 'பிரதமர் ஃபசல் பீமா யோஜனா',
    pmFasalDesc: 'இயற்கை பேரிடர்கள் மற்றும் விளைச்சல் இழப்புகளுக்கு எதிரான விரிவான பயிர் காப்பீடு.',
    pmFasalBenefit1: 'குறைந்த பிரீமியம் விகிதங்கள்',
    pmFasalBenefit2: 'விரைவான உரிமைகோரல் தீர்வு',
    pmFasalBenefit3: 'தொழில்நுட்ப ஒருங்கிணைப்பு',
    kisanCredit: 'கிசான் கடன் அட்டை',
    kisanCreditDesc: 'விவசாய செலவுகள் மற்றும் விவசாய முதலீடுகளுக்கு குறைந்த வட்டி கடன்கள்.',
    kisanCreditBenefit1: 'எளிதான விண்ணப்பம்',
    kisanCreditBenefit2: 'நெகிழ்வான திருப்பிச் செலுத்துதல்',
    kisanCreditBenefit3: 'குறைந்த வட்டி விகிதங்கள்',
    helplineSupport: 'உதவி எண் ஆதரவு',
    helplineDesc: 'விண்ணப்பங்கள் மற்றும் கேள்விகளுக்கு உதவி பெறுங்கள்',
    digitalServices: 'டிஜிட்டல் சேவைகள்',
    digitalServicesDesc: 'அரசாங்க போர்ட்டல்கள் மூலம் ஆன்லைனில் சேவைகளை அணுகவும்',
    documentation: 'ஆவணப்படுத்தல்',
    documentationDesc: 'தேவையான ஆவணங்கள் மற்றும் தகுதி விதிகள்',
    downloadGuidelines: 'வழிகாட்டுதல்களை பதிவிறக்கவும்',
    
    modernFarming: 'நவீன விவசாய நுட்பங்கள்',
    modernFarmingDesc: 'துல்லிய விவசாயம், ஸ்மார்ட் பாசன அமைப்புகள் மற்றும் நிலையான விவசாய நடைமுறைகளை கற்றுக்கொள்ளுங்கள்.',
    cropCultivation: 'பயிர் சாகுபடி அடிப்படைகள்',
    cropCultivationDesc: 'விவசாயத்தில் ஆரம்பநிலைக்கு விரிவான படிப்படியான வீடியோ வழிகாட்டி.',
    icarResearch: 'ICAR ஆராய்ச்சி வளங்கள்',
    icarResearchDesc: 'மேம்பட்ட விவசாய ஆராய்ச்சி, வெளியீடுகள் மற்றும் நிபுணர் வழிகாட்டுதல்களை அணுகவும்.',
    ministryGuidelines: 'அமைச்சக வழிகாட்டுதல்கள்',
    ministryGuidelinesDesc: 'அதிகாரப்பூர்வ கொள்கைகள், சமீபத்திய விவசாய வழிகாட்டுதல்கள் மற்றும் அரசாங்க முன்முயற்சிகள்.',
    videoCourse: 'வீடியோ பாடநெறி',
    videoSeries: 'வீடியோ தொடர்',
    researchPortal: 'ஆராய்ச்சி போர்ட்டல்',
    documentationType: 'ஆவணப்படுத்தல்',
    selfPaced: 'சுய-வேக',
    reference: 'குறிப்பு',
    beginner: 'ஆரம்பநிலை',
    intermediate: 'இடைநிலை',
    advanced: 'மேம்பட்ட',
    allLevels: 'அனைத்து நிலைகளும்',
    beginnerFarmer: 'ஆரம்ப விவசாயி',
    beginnerDesc: 'உங்கள் விவசாய பயணத்தைத் தொடங்குங்கள்',
    advancedTechniques: 'மேம்பட்ட நுட்பங்கள்',
    advancedDesc: 'நவீன விவசாய முறைகள்',
    agriBusiness: 'விவசாய வணிகம்',
    agriBusinessDesc: 'வணிக விவசாய உத்திகள்',
    basicFarming: 'அடிப்படை விவசாயம்',
    soilBasics: 'மண் அடிப்படைகள்',
    cropSelection: 'பயிர் தேர்வு',
    precisionFarming: 'துல்லிய விவசாயம்',
    iotAgriculture: 'விவசாயத்தில் IoT',
    dataAnalytics: 'தரவு பகுப்பாய்வு',
    marketAnalysis: 'சந்தை பகுப்பாய்வு',
    supplyChain: 'விநியோகச் சங்கிலி',
    financialPlanning: 'நிதித் திட்டமிடல்',
    tutorialsCount: 'பயிற்சிகள்',
    learnersCount: 'கற்பவர்கள்',
    expertsCount: 'நிபுணர்கள்',
    rating: 'மதிப்பீடு',
    
    ourMission: 'எங்கள் இலக்கு',
    missionDesc: 'விவசாயத்தை மிகவும் புத்திசாலித்தனமாகவும், நிலையானதாகவும் மற்றும் லாபகரமாகவும் செய்ய அதிநவீன AI தொழில்நுட்பத்துடன் விவசாயிகளை வலுப்படுத்துதல்.',
    innovation: 'புதுமை',
    innovationDesc: 'பாரம்பரிய விவசாய நடைமுறைகளை மாற்றி, புரட்சிகர AI/ML தொழில்நுட்பத்தை நேரடியாக வயல்களுக்கு கொண்டு வருதல்.',
    community: 'சமூகம்',
    communityDesc: 'விவசாய நிபுணர்கள், ஆராய்ச்சியாளர்கள் மற்றும் நவீன வளங்களுடன் விவசாயிகளை இணைக்கும் வலுவான வலையமைப்பை உருவாக்குதல்.',
    sustainability: 'நிலைத்தன்மை',
    sustainabilityDesc: 'எதிர்கால சந்ததியினருக்காக நம் சுற்றுச்சூழலைப் பாதுகாக்கும் சுற்றுச்சூழல் நட்பு விவசாய நடைமுறைகளை ஊக்குவித்தல்.',
    reliablePredictions: 'நம்பகமான கணிப்புகள்',
    reliableDesc: 'பரந்த விவசாய தரவுத்தொகுப்புகளில் பயிற்சி பெற்ற AI மாதிரிகள்',
    fastProcessing: 'வேகமான செயலாக்கம்',
    fastDesc: 'உடனடி பரிந்துரைகள் மற்றும் விளைச்சல் கணிப்புகள்',
    wideCoverage: 'பரந்த கவரேஜ்',
    wideDesc: 'பல பகுதிகளில் விவசாயிகளை ஆதரித்தல்',
    userSatisfaction: 'பயனர் திருப்தி',
    satisfactionDesc: 'விவசாய சமூகத்திலிருந்து நேர்மறையான கருத்துக்கள்',
    aiTeam: 'AI ஆராய்ச்சி குழு',
    aiTeamRole: 'மேம்பட்ட கணிப்பு மாதிரிகளை உருவாக்குதல்',
    aiExpertise: 'இயந்திர கற்றல் மற்றும் விவசாயம்',
    agriExperts: 'விவசாய நிபுணர்கள்',
    agriExpertsRole: 'களப் பரிச்சயத்தை வழங்குதல்',
    agriExpertise: 'பயிர் அறிவியல் மற்றும் மண் மேலாண்மை',
    designTeam: 'வடிவமைப்பு குழு',
    designTeamRole: 'உள்ளுணர்வு பயனர் அனுபவங்களை உருவாக்குதல்',
    designExpertise: 'UX/UI மற்றும் தயாரிப்பு வடிவமைப்பு',
    trustedFarmers: '10,000+ விவசாயிகளால் நம்பப்படுகிறது',
    uptimeGuarantee: '99.9% செயல்பாட்டு காலம் உத்தரவாதம்',
    
    email: 'மின்னஞ்சல்',
    phone: 'தொலைபேசி',
    socialMedia: 'சமூக ஊடகம்',
    supportHours: 'ஆதரவு நேரங்கள்',
    supportHoursDesc: 'திங்கள் - வெள்ளி: காலை 9:00 - மாலை 6:00 IST',
    location: 'இடம்',
    locationDesc: 'இந்தியா முழுவதும் விவசாயிகளுக்கு சேவை செய்தல்',
    responseTime: 'பதில் நேரம்',
    responseTimeDesc: '2 மணி நேரத்திற்குள் சராசரி பதில்',
    faqQ1: 'பயிர் பரிந்துரைகள் எவ்வளவு துல்லியமானவை?',
    faqA1: 'விரிவான சோதனையின் அடிப்படையில் எங்கள் AI மாதிரிகள் 95% துல்லியத்தை அடைகின்றன.',
    faqQ2: 'ஃபார்ம் ஃப்யூஷன் பயன்படுத்த இலவசமா?',
    faqA2: 'ஆம்! அனைத்து விவசாயிகளுக்கும் அடிப்படை அம்சங்கள் முற்றிலும் இலவசம்.',
    faqQ3: 'நீங்கள் எந்த மொழிகளை ஆதரிக்கிறீர்கள்?',
    faqA3: 'நாங்கள் ஆங்கிலம், இந்தி, தமிழ், வங்காளம் மற்றும் மராத்தி ஆகியவற்றை ஆதரிக்கிறோம்.',
    faqQ4: 'நான் தொழில்நுட்ப ஆதரவை எவ்வாறு பெறுவது?',
    faqA4: 'உடனடி உதவிக்காக தொலைபேசி அல்லது மின்னஞ்சல் மூலம் எங்களைத் தொடர்பு கொள்ளவும்.',
    nameRequired: 'பெயர் தேவை',
    nameRequiredDesc: 'தயவுசெய்து உங்கள் பெயரை உள்ளிடவும்',
    invalidEmail: 'தவறான மின்னஞ்சல்',
    invalidEmailDesc: 'தயவுசெய்து சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்',
    messageRequired: 'செய்தி தேவை',
    messageRequiredDesc: 'தயவுசெய்து உங்கள் செய்தியை உள்ளிடவும்',
    messageSent: 'செய்தி அனுப்பப்பட்டது! ✅',
    messageSentDesc: 'நாங்கள் விரைவில் உங்களைத் தொடர்புகொள்வோம்.',
    
    'soilAnalysis.title': 'AI மண் பகுப்பாய்வு',
    'soilAnalysis.description': 'உடனடி பகுப்பாய்வுக்காக உங்கள் மண்ணின் புகைப்படத்தை எடுக்கவும் அல்லது படத்தை பதிவேற்றவும்',
    'soilAnalysis.camera': 'கேமராவைப் பயன்படுத்தவும்',
    'soilAnalysis.capture': 'புகைப்படம் எடுக்கவும்',
    'soilAnalysis.upload': 'படத்தைப் பதிவேற்றவும்',
    'soilAnalysis.getWeather': 'இடத்திலிருந்து வானிலை தரவைப் பெறவும்',
    'soilAnalysis.success': 'பகுப்பாய்வு முடிந்தது!',
    'soilAnalysis.successDesc': 'மண் தரவு பகுப்பாய்வு செய்யப்பட்டு படிவத்தில் நிரப்பப்பட்டுள்ளது.',
    'soilAnalysis.error': 'பகுப்பாய்வு தோல்வியுற்றது',
    'soilAnalysis.cameraError': 'கேமரா பிழை',
    'soilAnalysis.cameraErrorDesc': 'கேமராவை அணுக முடியவில்லை',
    'soilAnalysis.results': 'பகுப்பாய்வு முடிவுகள்',
    'soilAnalysis.soilType': 'மண் வகை',
    'soilAnalysis.moisture': 'ஈரப்பதம்',
    'soilAnalysis.health': 'ஆரோக்கியம்',
    'soilAnalysis.recommendations': 'பரிந்துரைகள்',
    'weather.success': 'வானிலை தரவு மீட்டெடுக்கப்பட்டது!',
    'weather.successDesc': 'சுற்றுச்சூழல் தரவு படிவத்தில் நிரப்பப்பட்டுள்ளது.',
    'weather.error': 'இடப் பிழை',
    'weather.errorDesc': 'உங்கள் இடத்தைப் பெற முடியவில்லை',

    // Weather Alerts Section
    'weatherAlerts.title': 'வானிலை மற்றும் ஸ்மார்ட் நடவு வழிகாட்டி',
    'weatherAlerts.subtitle': 'AI-இயக்கப்படும் சிறந்த நடவு நேர பரிந்துரைகளுடன் 7-நாள் முன்னறிவிப்பு',
    'weatherAlerts.currentWeather': 'தற்போதைய வானிலை',
    'weatherAlerts.cropProtection': 'பயிர் பாதுகாப்பு எச்சரிக்கைகள்',
    'weatherAlerts.temperature': 'வெப்பநிலை',
    'weatherAlerts.humidity': 'ஈரப்பதம்',
    'weatherAlerts.rainfall': 'மழைப்பொழிவு (இன்று)',
    'weatherAlerts.forecast': '7-நாள் வானிலை முன்னறிவிப்பு',
    'weatherAlerts.plantingSuggestions': 'சிறந்த நடவு பரிந்துரைகள்',
    'weatherAlerts.avgHigh': 'சராசரி உயர்',
    'weatherAlerts.avgLow': 'சராசரி குறை',
    'weatherAlerts.totalRain': 'மொத்த மழை',
    'weatherAlerts.rainChance': 'மழை வாய்ப்பு',
    'weatherAlerts.bestDays': 'இந்த வாரம் நடவுக்கு சிறந்த நாட்கள்',
    'weatherAlerts.irrigationSchedule': 'ஸ்மார்ட் பாசன அட்டவணை',
    'weatherAlerts.dailySchedule': 'தினசரி பாசன அட்டவணை',
    'weatherAlerts.weeklyNeeds': 'வாராந்திர நீர் தேவை',
    'weatherAlerts.soilMoisture': 'மண் ஈரப்பத கணிப்பு',
    'weatherAlerts.irrigationTips': 'பாசன குறிப்புகள்',
    'weatherAlerts.loading': 'வானிலை தரவு ஏற்றப்படுகிறது...',
    'weatherAlerts.clickRefresh': 'வானிலை தரவை ஏற்ற புதுப்பிக்கவும்',
    'weatherAlerts.weatherUpdated': 'வானிலை புதுப்பிக்கப்பட்டது!',
    'weatherAlerts.highTemp': 'உயர் வெப்பநிலை எச்சரிக்கை! பாசனம் செய்யுங்கள்.',
    'weatherAlerts.lowTemp': 'குறைந்த வெப்பநிலை எச்சரிக்கை! பயிர்களை பாதுகாக்கவும்.',
    'weatherAlerts.highHumidity': 'அதிக ஈரப்பதம்! பூஞ்சை நோய் ஆபத்து.',
    'weatherAlerts.heavyRain': 'கனமழை எதிர்பார்க்கப்படுகிறது! வடிகால் உறுதிசெய்யவும்.',
    'weatherAlerts.dryConditions': 'வறண்ட நிலை! பாசன திட்டமிடுங்கள்.',
    'weatherAlerts.favorable': 'வானிலை விவசாயத்திற்கு சாதகமாக உள்ளது.',
    
    // Yield Prediction Section
    'yield.calculating': 'விளைச்சல் கணக்கிடப்படுகிறது...',
    'yield.dataAutoFilled': 'தரவு தானாக நிரப்பப்பட்டது!',
    'yield.dataAutoFilledDesc': 'பயிர் தரவு ஏற்றப்பட்டது. பூச்சிக்கொல்லி மற்றும் பரப்பளவு சேர்க்கவும்.',
    'yield.missingInfo': 'தகவல் இல்லை',
    'yield.fillAllFields': 'அனைத்து தேவையான புலங்களையும் நிரப்பவும்.',
    'yield.predictionReady': 'விளைச்சல் கணிப்பு தயார்!',
    'yield.expectedYield': 'எதிர்பார்க்கப்படும் விளைச்சல்',
    'yield.error': 'விளைச்சல் கணிப்பு தோல்வி. மீண்டும் முயற்சிக்கவும்.',
    'yield.cropName': 'பயிர் பெயர்',
    'yield.year': 'ஆண்டு',
    'yield.rainfall': 'மழைப்பொழிவு',
    'yield.pesticide': 'பூச்சிக்கொல்லி பயன்பாடு',
    'yield.temperature': 'வெப்பநிலை',
    'yield.area': 'பரப்பளவு',
    'yield.viewHistory': 'வரலாறு காண்க',
    'yield.hideHistory': 'வரலாறு மறை',
    'yield.recentPredictions': 'சமீபத்திய கணிப்புகள்',
    'yield.deleted': 'நீக்கப்பட்டது',
    'yield.removedFromHistory': 'கணிப்பு வரலாற்றில் இருந்து நீக்கப்பட்டது',
    'yield.weatherImpact': 'வானிலை தாக்கம்',
    'yield.weatherImpactDesc': 'மழை முறைகள் வளர்ச்சி சுழற்சிகளை பாதிக்கின்றன',
    'yield.tempImpact': 'வெப்பநிலை',
    'yield.tempImpactDesc': 'சிறந்த வெப்பநிலை விளைச்சலை அதிகரிக்கிறது',
    'yield.pesticideImpact': 'பூச்சிக்கொல்லி பயன்பாடு',
    'yield.pesticideImpactDesc': 'சரியான பூச்சி கட்டுப்பாடு உற்பத்தியை அதிகரிக்கிறது',
    'yield.areaEfficiency': 'பரப்பளவு திறன்',
    'yield.areaEfficiencyDesc': 'நில பயன்பாட்டு மேம்படுத்தல்',
    'yield.aiRecommendations': 'AI-இயக்கப்படும் பரிந்துரைகள்',

    // Crop Recommendation Section
    'crop.analyzingSoil': 'மண் பகுப்பாய்வு செய்யப்படுகிறது...',
    'crop.recommendationGenerated': 'பரிந்துரை உருவாக்கப்பட்டது!',
    'crop.basedOnSoil': 'உங்கள் மண் நிலைமைகளின் அடிப்படையில், நாங்கள் பரிந்துரைக்கிறோம்',
    'crop.growthDuration': 'வளர்ச்சி காலம்',
    'crop.approximately': 'தோராயமாக',
    'crop.days': 'நாட்கள்',
    'crop.useForYield': 'விளைச்சல் கணிப்புக்கு பயன்படுத்தவும்',
    'crop.marketInsights': 'சந்தை விலை நுண்ணறிவு',
    'crop.currentPrice': 'தற்போதைய விலை',
    'crop.avgPrice': 'சராசரி விலை (12 மாதம்)',
    'crop.bestSellTime': 'விற்க சிறந்த நேரம்',
    'crop.priceHistory': '12-மாத விலை போக்கு',
    'crop.recommendation': 'பரிந்துரை',
    'crop.soilAnalysis': 'மண் பகுப்பாய்வு',
    'crop.soilAnalysisDesc': 'NPK அளவுகள் ஊட்டச்சத்து கிடைக்கும் தன்மையை தீர்மானிக்கின்றன',
    'crop.climateFactors': 'காலநிலை காரணிகள்',
    'crop.climateFactorsDesc': 'வெப்பநிலை மற்றும் ஈரப்பதம் வளர்ச்சியை பாதிக்கின்றன',
    'crop.waterManagement': 'நீர் மேலாண்மை',
    'crop.waterManagementDesc': 'மழை முறைகள் பாசன தேவைகளை வழிநடத்துகின்றன',
    'crop.phBalance': 'pH சமநிலை',
    'crop.phBalanceDesc': 'சிறந்த pH ஊட்டச்சத்து உறிஞ்சுதலை உறுதிசெய்கிறது',
    'crop.nitrogen': 'நைட்ரஜன் (N)',
    'crop.phosphorus': 'பாஸ்பரஸ் (P)',
    'crop.potassium': 'பொட்டாசியம் (K)',
    'crop.humidity': 'ஈரப்பதம்',
    'crop.phValue': 'pH மதிப்பு',

    // Chatbot
    'chatbot.title': 'நெட்யா - விவசாய உதவியாளர்',
    'chatbot.placeholder': 'நெட்யாவிடம் விவசாயம் பற்றி கேளுங்கள்...',
    'chatbot.listening': 'கேட்கிறது...',
    'chatbot.speakNow': 'இப்போது பேசுங்கள்',
    'chatbot.greeting': 'வணக்கம்! நான் நெட்யா',
    'chatbot.askAnything': 'விவசாயம் பற்றி எதையும் கேளுங்கள்!',
    'chatbot.topics': 'பயிர்கள் • வானிலை • பூச்சிகள் • மண் • நுட்பங்கள்',
    'chatbot.voiceSupport': '5 மொழிகளில் பேசுங்கள் அல்லது தட்டச்சு செய்யுங்கள்',
    'chatbot.language': 'மொழி',
    'chatbot.stop': 'நிறுத்து',
    'nav.login': 'உள்நுழைவு',
    'nav.logout': 'வெளியேறு',
    'nav.loginSignup': 'உள்நுழைவு / பதிவு',
    'nav.welcome': 'வரவேற்கிறோம்',
    'nav.hello': 'வணக்கம்',
    'crop.yourLocation': 'உங்கள் இருப்பிடம்',
    'crop.forMarketPrices': 'சந்தை விலைகளுக்கு',
    'crop.locationPlaceholder': 'எ.கா. புனே, மகாராஷ்டிரா',
    'crop.useCurrentLocation': 'தற்போதைய இருப்பிடத்தைப் பயன்படுத்தவும்',
    'crop.geolocationNotSupported': 'புவி இருப்பிடம் ஆதரிக்கப்படவில்லை',
    'crop.couldNotGetLocation': 'இருப்பிடத்தைப் பெற முடியவில்லை',
    'crop.locationRequired': 'இருப்பிடம் தேவை',
    'crop.locationRequiredDesc': 'அருகிலுள்ள சந்தைகளை கண்டறிய உங்கள் இருப்பிடத்தை உள்ளிடவும்.',
    'crop.nearbyMarkets': 'அருகிலுள்ள சந்தைகள் மற்றும் வாங்குபவர்கள்',
    'crop.findingMarkets': 'உங்களுக்கு அருகிலுள்ள சிறந்த சந்தைகளை கண்டறிகிறது...',
    'crop.avgPriceShort': 'சராசரி விலை',
    'crop.transport': 'போக்குவரத்து',
    'crop.error': 'பிழை',
    'crop.errorDesc': 'பரிந்துரையை உருவாக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'crop.marketsUnavailable': 'சந்தைகள் கிடைக்கவில்லை',
    'crop.couldNotFetchMarkets': 'சந்தைகளைப் பெற முடியவில்லை',
    'cropName.Rice': 'அரிசி',
    'cropName.Wheat': 'கோதுமை',
    'cropName.Corn': 'சோளம்',
    'cropName.Barley': 'வாற்கோதுமை',
    'cropName.Sugarcane': 'கரும்பு',
    'cropName.Cotton': 'பருத்தி',
    'cropName.Tomato': 'தக்காளி',
    'cropName.Potato': 'உருளைக்கிழங்கு',
    'crop.months': 'மாதங்கள்',
    'crop.trendUp': 'உயர்கிறது',
    'crop.trendDown': 'குறைகிறது',
    'crop.trendStable': 'நிலையானது',
    'crop.pricesAboveAvg': 'விலைகள் சராசரிக்கு மேல் உள்ளன. விரைவில் விற்க பரிசீலிக்கவும்.',
    'crop.pricesBelowAvg': 'விலைகள் சராசரிக்கு கீழே உள்ளன. உச்ச மாதங்களில் விற்பது சிறந்தது.',
    'crop.pricesStable': 'நிலையான விலைகள். சிறந்த வருமானத்திற்கு உச்ச மாதங்களில் விற்கவும்.',
    'crop.perQuintal': '/குவிண்டால்',
  },
  bn: {
    home: 'হোম',
    recommend: 'ফসল সুপারিশ',
    predict: 'উৎপাদন পূর্বাভাস',
    weatherAlerts: 'আবহাওয়া',
    schemes: 'যোজনা',
    tutorials: 'টিউটোরিয়াল',
    about: 'আমাদের সম্পর্কে',
    contact: 'যোগাযোগ',
    title: 'ফার্মফিউশন 🌱',
    subtitle: 'কৃষকদের AI দিয়ে ফসল সুপারিশ, উৎপাদন পূর্বাভাস এবং সরকারি যোজনায় সাহায্য।',
    btnRec: 'সুপারিশ পান',
    btnYield: 'ফসল অনুমান',
    heroTitle: 'ফার্মফিউশন',
    heroSubtitle: 'টেকসই কৃষির জন্য AI-চালিত ফসল সুপারিশ, উৎপাদন পূর্বাভাস এবং সরকারি প্রকল্পগুলিতে নিরবচ্ছিন্ন অ্যাক্সেসের সাথে কৃষকদের ক্ষমতায়ন।',
    startJourney: 'আপনার যাত্রা শুরু করুন',
    learnMore: 'আরও জানুন',
    heroStatFarmers: 'সহায়তা প্রাপ্ত কৃষক',
    heroStatCrops: 'ফসলের ধরন',
    heroStatAccuracy: 'নির্ভুলতা',
    heroStatSchemes: 'সরকারি প্রকল্প',
    cropTitle: 'স্মার্ট ফসল সুপারিশ',
    cropSubtitle: 'আপনার মাটির অবস্থা এবং পরিবেশগত উপাদানের উপর ভিত্তি করে AI-চালিত ফসল সুপারিশ পান।',
    soilEnvData: 'মাটি ও পরিবেশের ডেটা',
    recommendedCrop: 'প্রস্তাবিত ফসল',
    optimalForConditions: 'এই ফসলটি আপনার বর্তমান মাটি ও পরিবেশগত অবস্থার জন্য উপযুক্ত।',
    yieldTitle: 'স্মার্ট উৎপাদন পূর্বাভাস',
    yieldSubtitle: 'পরিবেশগত উপাদান এবং কৃষি অনুশীলনের উপর ভিত্তি করে উন্নত AI মডেল দিয়ে আপনার ফসলের উৎপাদন পূর্বাভাস দিন।',
    cropEnvData: 'ফসল ও পরিবেশের ডেটা',
    predictedYield: 'প্রত্যাশিত উৎপাদন',
    accuracyRate: 'নির্ভুলতার হার',
    schemesTitle: 'সরকারি প্রকল্প এবং সহায়তা',
    schemesSubtitle: 'সারা ভারত জুড়ে কৃষকদের ক্ষমতায়নের জন্য ডিজাইন করা ব্যাপক কৃষি নীতি, ভর্তুকি এবং সহায়তা কর্মসূচি অন্বেষণ করুন।',
    keyBenefits: 'মূল সুবিধা',
    applyNow: 'এখনই আবেদন করুন',
    tutorialsTitle: 'বিস্তৃত শিক্ষা কেন্দ্র',
    tutorialsSubtitle: 'বিশেষজ্ঞ-নির্বাচিত টিউটোরিয়াল, গবেষণা পত্র এবং ইন্টারঅ্যাক্টিভ শিক্ষা মডিউলের মাধ্যমে আধুনিক কৃষি কৌশলগুলি আয়ত্ত করুন।',
    startLearning: 'শেখা শুরু করুন',
    learningPaths: 'কাঠামোগত শিক্ষার পথ',
    aboutTitle: 'সম্পর্কে',
    aboutSubtitle: 'আমরা কৃত্রিম বুদ্ধিমত্তার মাধ্যমে কৃষিতে বিপ্লব ঘটানোর মিশনে আছি, যা বিশ্বব্যাপী কৃষকদের জন্য চাষকে আরও দক্ষ, টেকসই এবং লাভজনক করে তুলছে।',
    whyChoose: 'ফার্মফিউশন কেন বেছে নেবেন?',
    ourTeam: 'আমাদের বিশেষজ্ঞ দল',
    joinRevolution: 'কৃষি বিপ্লবে যোগ দিন',
    revolutionText: 'চাষের ভবিষ্যতের একটি অংশ হন। একসাথে, আমরা সবার জন্য আরও টেকসই এবং সমৃদ্ধ কৃষি বাস্তুতন্ত্র তৈরি করছি।',
    contactTitle: 'যোগাযোগে থাকুন',
    contactSubtitle: 'প্রশ্ন আছে বা সহায়তা প্রয়োজন? আমরা আপনাকে ফার্মফিউশনের সর্বাধিক ব্যবহার করতে সাহায্য করতে এখানে আছি। ব্যক্তিগত সহায়তার জন্য আমাদের দলের সাথে যোগাযোগ করুন।',
    quickMessage: 'দ্রুত বার্তা',
    yourName: 'আপনার নাম',
    yourEmail: 'আপনার ইমেল',
    yourMessage: 'আপনার বার্তা',
    sending: 'পাঠানো হচ্ছে...',
    sendMessage: 'বার্তা পাঠান',
    faq: 'প্রায়শই জিজ্ঞাসিত প্রশ্ন',
    growingTogether: 'একসাথে বৃদ্ধি',
    thankYou: 'ফার্মফিউশন সম্প্রদায়ের অংশ হওয়ার জন্য আপনাকে ধন্যবাদ। একসাথে, আমরা কৃষির জন্য একটি স্মার্ট, আরও টেকসই ভবিষ্যত তৈরি করছি।',
    
    pmKisan: 'পিএম-কিষাণ যোজনা',
    pmKisanDesc: 'ক্ষুদ্র ও প্রান্তিক কৃষকদের সরাসরি ₹6,000 বার্ষিক আর্থিক সহায়তা।',
    pmKisanBenefit1: 'সরাসরি সুবিধা স্থানান্তর',
    pmKisanBenefit2: 'কোন মধ্যস্থতাকারী নেই',
    pmKisanBenefit3: 'সারা ভারতে কভারেজ',
    soilHealth: 'মৃত্তিকা স্বাস্থ্য কার্ড',
    soilHealthDesc: 'ব্যাপক মাটি পরীক্ষা এবং ফসল-নির্দিষ্ট সুপারিশ।',
    soilHealthBenefit1: 'বিনামূল্যে মাটি পরীক্ষা',
    soilHealthBenefit2: 'পুষ্টি ব্যবস্থাপনা',
    soilHealthBenefit3: 'ফলন উন্নতি',
    pmFasal: 'পিএম ফসল বীমা যোজনা',
    pmFasalDesc: 'প্রাকৃতিক দুর্যোগ এবং ফলন ক্ষতির বিরুদ্ধে ব্যাপক ফসল বীমা।',
    pmFasalBenefit1: 'কম প্রিমিয়াম হার',
    pmFasalBenefit2: 'দ্রুত দাবি নিষ্পত্তি',
    pmFasalBenefit3: 'প্রযুক্তি একীকরণ',
    kisanCredit: 'কিষাণ ক্রেডিট কার্ড',
    kisanCreditDesc: 'কৃষি খরচ এবং বিনিয়োগের জন্য কম সুদের ঋণ।',
    kisanCreditBenefit1: 'সহজ আবেদন',
    kisanCreditBenefit2: 'নমনীয় পরিশোধ',
    kisanCreditBenefit3: 'কম সুদের হার',
    helplineSupport: 'হেল্পলাইন সহায়তা',
    helplineDesc: 'আবেদন এবং প্রশ্নগুলির সাথে সহায়তা পান',
    digitalServices: 'ডিজিটাল সেবা',
    digitalServicesDesc: 'সরকারী পোর্টালগুলির মাধ্যমে অনলাইনে সেবা অ্যাক্সেস করুন',
    documentation: 'নথিপত্র',
    documentationDesc: 'প্রয়োজনীয় নথি এবং যোগ্যতার মানদণ্ড',
    downloadGuidelines: 'নির্দেশিকা ডাউনলোড করুন',
    modernFarming: 'আধুনিক কৃষি কৌশল',
    modernFarmingDesc: 'নির্ভুল কৃষি, স্মার্ট সেচ ব্যবস্থা এবং টেকসই কৃষি অনুশীলন শিখুন।',
    cropCultivation: 'ফসল চাষের মূল বিষয়',
    cropCultivationDesc: 'কৃষিতে নতুনদের জন্য ব্যাপক ধাপে ধাপে ভিডিও গাইড।',
    icarResearch: 'ICAR গবেষণা সংস্থান',
    icarResearchDesc: 'উন্নত কৃষি গবেষণা, প্রকাশনা এবং বিশেষজ্ঞ নির্দেশনা অ্যাক্সেস করুন।',
    ministryGuidelines: 'মন্ত্রণালয় নির্দেশিকা',
    ministryGuidelinesDesc: 'সরকারী নীতি, সর্বশেষ কৃষি নির্দেশিকা এবং সরকারী উদ্যোগ।',
    videoCourse: 'ভিডিও কোর্স',
    videoSeries: 'ভিডিও সিরিজ',
    researchPortal: 'গবেষণা পোর্টাল',
    documentationType: 'নথিপত্র',
    selfPaced: 'স্ব-গতিসম্পন্ন',
    reference: 'রেফারেন্স',
    beginner: 'শুরুর স্তর',
    intermediate: 'মধ্যবর্তী',
    advanced: 'উন্নত',
    allLevels: 'সব স্তর',
    beginnerFarmer: 'শুরুর কৃষক',
    beginnerDesc: 'আপনার কৃষি যাত্রা শুরু করুন',
    advancedTechniques: 'উন্নত কৌশল',
    advancedDesc: 'আধুনিক কৃষি পদ্ধতি',
    agriBusiness: 'কৃষি ব্যবসা',
    agriBusinessDesc: 'বাণিজ্যিক কৃষি কৌশল',
    basicFarming: 'মৌলিক কৃষি',
    soilBasics: 'মাটির মূল বিষয়',
    cropSelection: 'ফসল নির্বাচন',
    precisionFarming: 'নির্ভুল কৃষি',
    iotAgriculture: 'কৃষিতে IoT',
    dataAnalytics: 'ডেটা বিশ্লেষণ',
    marketAnalysis: 'বাজার বিশ্লেষণ',
    supplyChain: 'সরবরাহ শৃঙ্খল',
    financialPlanning: 'আর্থিক পরিকল্পনা',
    tutorialsCount: 'টিউটোরিয়াল',
    learnersCount: 'শিক্ষার্থী',
    expertsCount: 'বিশেষজ্ঞ',
    rating: 'রেটিং',
    ourMission: 'আমাদের লক্ষ্য',
    missionDesc: 'কৃষিকে আরও স্মার্ট, টেকসই এবং লাভজনক করতে অত্যাধুনিক AI প্রযুক্তি দিয়ে কৃষকদের ক্ষমতায়ন করা।',
    innovation: 'উদ্ভাবন',
    innovationDesc: 'ঐতিহ্যবাহী কৃষি অনুশীলনকে রূপান্তরিত করে, বিপ্লবী AI/ML প্রযুক্তি সরাসরি ক্ষেতে নিয়ে আসা।',
    community: 'সম্প্রদায়',
    communityDesc: 'কৃষি বিশেষজ্ঞ, গবেষক এবং আধুনিক সংস্থানগুলির সাথে কৃষকদের সংযুক্ত করে একটি শক্তিশালী নেটওয়ার্ক তৈরি করা।',
    sustainability: 'স্থায়িত্ব',
    sustainabilityDesc: 'পরিবেশ বান্ধব কৃষি অনুশীলনগুলি প্রচার করা যা ভবিষ্যত প্রজন্মের জন্য আমাদের পরিবেশকে রক্ষা করে।',
    reliablePredictions: 'নির্ভরযোগ্য পূর্বাভাস',
    reliableDesc: 'বিশাল কৃষি ডেটাসেটে প্রশিক্ষিত AI মডেল',
    fastProcessing: 'দ্রুত প্রক্রিয়াকরণ',
    fastDesc: 'তাৎক্ষণিক সুপারিশ এবং ফলন পূর্বাভাস',
    wideCoverage: 'বিস্তৃত কভারেজ',
    wideDesc: 'একাধিক অঞ্চলে কৃষকদের সমর্থন করা',
    userSatisfaction: 'ব্যবহারকারীর সন্তুষ্টি',
    satisfactionDesc: 'কৃষি সম্প্রদায় থেকে ইতিবাচক প্রতিক্রিয়া',
    aiTeam: 'AI গবেষণা দল',
    aiTeamRole: 'উন্নত পূর্বাভাস মডেল উন্নয়ন করা',
    aiExpertise: 'মেশিন লার্নিং এবং কৃষি',
    agriExperts: 'কৃষি বিশেষজ্ঞ',
    agriExpertsRole: 'ডোমেইন ज्ञান প্রদান করা',
    agriExpertise: 'ফসল বিজ্ঞান এবং মাটি ব্যবস্থাপনা',
    designTeam: 'ডিজাইন দল',
    designTeamRole: 'স্বজ্ঞাত ব্যবহারকারীর অভিজ্ঞতা তৈরি করা',
    designExpertise: 'UX/UI এবং পণ্য ডিজাইন',
    trustedFarmers: '10,000+ কৃষক দ্বারা বিশ্বস্ত',
    uptimeGuarantee: '99.9% আপটাইম গ্যারান্টি',
    email: 'ইমেইল',
    phone: 'ফোন',
    socialMedia: 'সামাজিক মাধ্যম',
    supportHours: 'সহায়তা সময়',
    supportHoursDesc: 'সোমবার - শুক্রবার: সকাল 9:00 - সন্ধ্যা 6:00 IST',
    location: 'অবস্থান',
    locationDesc: 'সারা ভারতে কৃষকদের সেবা করা',
    responseTime: 'প্রতিক্রিয়া সময়',
    responseTimeDesc: '2 ঘন্টার মধ্যে গড় প্রতিক্রিয়া',
    faqQ1: 'ফসল সুপারিশগুলি কতটা সঠিক?',
    faqA1: 'ব্যাপক পরীক্ষার ভিত্তিতে আমাদের AI মডেল 95% নির্ভুলতা অর্জন করে।',
    faqQ2: 'ফার্মফিউশন ব্যবহার করা কি বিনামূল্যে?',
    faqA2: 'হ্যাঁ! সমস্ত কৃষকদের জন্য মৌলিক বৈশিষ্ট্যগুলি সম্পূর্ণ বিনামূল্যে।',
    faqQ3: 'আপনি কোন ভাষা সমর্থন করেন?',
    faqA3: 'আমরা ইংরেজি, হিন্দি, তামিল, বাংলা এবং মারাঠি সমর্থন করি।',
    faqQ4: 'আমি কীভাবে প্রযুক্তিগত সহায়তা পাব?',
    faqA4: 'তাৎক্ষণিক সহায়তার জন্য ফোন বা ইমেলের মাধ্যমে আমাদের সাথে যোগাযোগ করুন।',
    nameRequired: 'নাম প্রয়োজন',
    nameRequiredDesc: 'অনুগ্রহ করে আপনার নাম লিখুন',
    invalidEmail: 'অবৈধ ইমেল',
    invalidEmailDesc: 'অনুগ্রহ করে একটি বৈধ ইমেল ঠিকানা লিখুন',
    messageRequired: 'বার্তা প্রয়োজন',
    messageRequiredDesc: 'অনুগ্রহ করে আপনার বার্তা লিখুন',
    messageSent: 'বার্তা পাঠানো হয়েছে! ✅',
    messageSentDesc: 'আমরা শীঘ্রই আপনার সাথে যোগাযোগ করব।',
    'soilAnalysis.title': 'AI মাটি বিশ্লেষণ',
    'soilAnalysis.description': 'তাৎক্ষণিক বিশ্লেষণের জন্য আপনার মাটির ছবি তুলুন বা চিত্র আপলোড করুন',
    'soilAnalysis.camera': 'ক্যামেরা ব্যবহার করুন',
    'soilAnalysis.capture': 'ছবি তুলুন',
    'soilAnalysis.upload': 'চিত্র আপলোড করুন',
    'soilAnalysis.getWeather': 'অবস্থান থেকে আবহাওয়া ডেটা পান',
    'soilAnalysis.success': 'বিশ্লেষণ সম্পূর্ণ!',
    'soilAnalysis.successDesc': 'মাটির ডেটা বিশ্লেষণ করা হয়েছে এবং ফর্মে পূরণ করা হয়েছে।',
    'soilAnalysis.error': 'বিশ্লেষণ ব্যর্থ',
    'soilAnalysis.cameraError': 'ক্যামেরা ত্রুটি',
    'soilAnalysis.cameraErrorDesc': 'ক্যামেরা অ্যাক্সেস করতে পারেনি',
    'soilAnalysis.results': 'বিশ্লেষণ ফলাফল',
    'soilAnalysis.soilType': 'মাটির ধরন',
    'soilAnalysis.moisture': 'আর্দ্রতা',
    'soilAnalysis.health': 'স্বাস্থ্য',
    'soilAnalysis.recommendations': 'সুপারিশ',
    'weather.success': 'আবহাওয়া ডেটা পুনরুদ্ধার করা হয়েছে!',
    'weather.successDesc': 'পরিবেশগত ডেটা ফর্মে পূরণ করা হয়েছে।',
    'weather.error': 'অবস্থান ত্রুটি',
    'weather.errorDesc': 'আপনার অবস্থান পেতে পারেনি',

    // Weather Alerts Section
    'weatherAlerts.title': 'আবহাওয়া এবং স্মার্ট রোপণ গাইড',
    'weatherAlerts.subtitle': 'AI-চালিত সর্বোত্তম রোপণ সময় পরামর্শ সহ 7-দিনের পূর্বাভাস',
    'weatherAlerts.currentWeather': 'বর্তমান আবহাওয়া',
    'weatherAlerts.cropProtection': 'ফসল সুরক্ষা সতর্কতা',
    'weatherAlerts.temperature': 'তাপমাত্রা',
    'weatherAlerts.humidity': 'আর্দ্রতা',
    'weatherAlerts.rainfall': 'বৃষ্টিপাত (আজ)',
    'weatherAlerts.forecast': '7-দিনের আবহাওয়া পূর্বাভাস',
    'weatherAlerts.plantingSuggestions': 'সর্বোত্তম রোপণ পরামর্শ',
    'weatherAlerts.avgHigh': 'গড় উচ্চ',
    'weatherAlerts.avgLow': 'গড় নিম্ন',
    'weatherAlerts.totalRain': 'মোট বৃষ্টি',
    'weatherAlerts.rainChance': 'বৃষ্টির সম্ভাবনা',
    'weatherAlerts.bestDays': 'এই সপ্তাহে রোপণের জন্য সেরা দিন',
    'weatherAlerts.irrigationSchedule': 'স্মার্ট সেচ সময়সূচি',
    'weatherAlerts.dailySchedule': 'দৈনিক সেচ সময়সূচি',
    'weatherAlerts.weeklyNeeds': 'সাপ্তাহিক পানির প্রয়োজন',
    'weatherAlerts.soilMoisture': 'মাটির আর্দ্রতা পূর্বাভাস',
    'weatherAlerts.irrigationTips': 'সেচ পরামর্শ',
    'weatherAlerts.loading': 'আবহাওয়া ডেটা লোড হচ্ছে...',
    'weatherAlerts.clickRefresh': 'আবহাওয়া ডেটা লোড করতে রিফ্রেশ ক্লিক করুন',
    'weatherAlerts.weatherUpdated': 'আবহাওয়া আপডেট হয়েছে!',
    'weatherAlerts.highTemp': 'উচ্চ তাপমাত্রা সতর্কতা! সেচ বিবেচনা করুন এবং ফসলে ছায়া দিন।',
    'weatherAlerts.lowTemp': 'নিম্ন তাপমাত্রা সতর্কতা! ফসলকে তুষারপাত থেকে রক্ষা করুন।',
    'weatherAlerts.highHumidity': 'উচ্চ আর্দ্রতা শনাক্ত! ছত্রাক রোগের ঝুঁকি।',
    'weatherAlerts.heavyRain': 'ভারী বৃষ্টিপাত প্রত্যাশিত! সঠিক নিষ্কাশন নিশ্চিত করুন।',
    'weatherAlerts.dryConditions': 'শুষ্ক অবস্থা! সেচ পরিকল্পনা করুন।',
    'weatherAlerts.favorable': 'আবহাওয়া পরিস্থিতি কৃষির জন্য অনুকূল।',

    // Yield Prediction Section
    'yield.calculating': 'উৎপাদন গণনা হচ্ছে...',
    'yield.dataAutoFilled': 'ডেটা স্বয়ংক্রিয়ভাবে পূরণ হয়েছে!',
    'yield.dataAutoFilledDesc': 'ফসলের ডেটা লোড হয়েছে। অনুগ্রহ করে কীটনাশক এবং এলাকা যোগ করুন।',
    'yield.missingInfo': 'তথ্য অসম্পূর্ণ',
    'yield.fillAllFields': 'অনুগ্রহ করে সমস্ত প্রয়োজনীয় ক্ষেত্র পূরণ করুন।',
    'yield.predictionReady': 'উৎপাদন পূর্বাভাস প্রস্তুত!',
    'yield.expectedYield': 'প্রত্যাশিত উৎপাদন',
    'yield.error': 'উৎপাদন পূর্বাভাস ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    'yield.cropName': 'ফসলের নাম',
    'yield.year': 'বছর',
    'yield.rainfall': 'বৃষ্টিপাত',
    'yield.pesticide': 'কীটনাশক ব্যবহার',
    'yield.temperature': 'তাপমাত্রা',
    'yield.area': 'এলাকা',
    'yield.viewHistory': 'ইতিহাস দেখুন',
    'yield.hideHistory': 'ইতিহাস লুকান',
    'yield.recentPredictions': 'সাম্প্রতিক পূর্বাভাস',
    'yield.deleted': 'মুছে ফেলা হয়েছে',
    'yield.removedFromHistory': 'পূর্বাভাস ইতিহাস থেকে সরানো হয়েছে',
    'yield.weatherImpact': 'আবহাওয়া প্রভাব',
    'yield.weatherImpactDesc': 'বৃষ্টিপাতের ধরণ বৃদ্ধি চক্রকে প্রভাবিত করে',
    'yield.tempImpact': 'তাপমাত্রা',
    'yield.tempImpactDesc': 'সর্বোত্তম তাপমাত্রা উৎপাদন বাড়ায়',
    'yield.pesticideImpact': 'কীটনাশক ব্যবহার',
    'yield.pesticideImpactDesc': 'সঠিক কীট নিয়ন্ত্রণ উৎপাদন বাড়ায়',
    'yield.areaEfficiency': 'এলাকা দক্ষতা',
    'yield.areaEfficiencyDesc': 'জমি ব্যবহার অপ্টিমাইজেশন',
    'yield.aiRecommendations': 'AI-চালিত সুপারিশ',

    // Crop Recommendation Section
    'crop.analyzingSoil': 'মাটি বিশ্লেষণ হচ্ছে...',
    'crop.recommendationGenerated': 'সুপারিশ তৈরি হয়েছে!',
    'crop.basedOnSoil': 'আপনার মাটির অবস্থার উপর ভিত্তি করে, আমরা সুপারিশ করি',
    'crop.growthDuration': 'বৃদ্ধির সময়কাল',
    'crop.approximately': 'আনুমানিক',
    'crop.days': 'দিন',
    'crop.useForYield': 'উৎপাদন পূর্বাভাসের জন্য ব্যবহার করুন',
    'crop.marketInsights': 'বাজার মূল্য অন্তর্দৃষ্টি',
    'crop.currentPrice': 'বর্তমান মূল্য',
    'crop.avgPrice': 'গড় মূল্য (12 মাস)',
    'crop.bestSellTime': 'বিক্রির সেরা সময়',
    'crop.priceHistory': '12-মাসের মূল্য প্রবণতা',
    'crop.recommendation': 'সুপারিশ',
    'crop.soilAnalysis': 'মাটি বিশ্লেষণ',
    'crop.soilAnalysisDesc': 'NPK স্তর পুষ্টি উপলব্ধতা নির্ধারণ করে',
    'crop.climateFactors': 'জলবায়ু উপাদান',
    'crop.climateFactorsDesc': 'তাপমাত্রা এবং আর্দ্রতা বৃদ্ধিকে প্রভাবিত করে',
    'crop.waterManagement': 'জল ব্যবস্থাপনা',
    'crop.waterManagementDesc': 'বৃষ্টিপাতের ধরণ সেচ প্রয়োজনীয়তা নির্দেশ করে',
    'crop.phBalance': 'pH ভারসাম্য',
    'crop.phBalanceDesc': 'সর্বোত্তম pH পুষ্টি শোষণ নিশ্চিত করে',
    'crop.nitrogen': 'নাইট্রোজেন (N)',
    'crop.phosphorus': 'ফসফরাস (P)',
    'crop.potassium': 'পটাসিয়াম (K)',
    'crop.humidity': 'আর্দ্রতা',
    'crop.phValue': 'pH মান',

    // Chatbot
    'chatbot.title': 'আদিই - কৃষি সহকারী',
    'chatbot.placeholder': 'আদিইকে কৃষি সম্পর্কে জিজ্ঞাসা করুন...',
    'chatbot.listening': 'শুনছে...',
    'chatbot.speakNow': 'এখন বলুন',
    'chatbot.greeting': 'হ্যালো! আমি আদিই',
    'chatbot.askAnything': 'কৃষি সম্পর্কে যেকোনো কিছু জিজ্ঞাসা করুন!',
    'chatbot.topics': 'ফসল • আবহাওয়া • কীটপতঙ্গ • মাটি • কৌশল',
    'chatbot.voiceSupport': '5টি ভাষায় বলুন বা টাইপ করুন',
    'chatbot.language': 'ভাষা',
    'chatbot.stop': 'থামুন',
    'nav.login': 'লগইন',
    'nav.logout': 'লগআউট',
    'nav.loginSignup': 'লগইন / সাইন আপ',
    'nav.welcome': 'স্বাগতম',
    'nav.hello': 'হ্যালো',
    'crop.yourLocation': 'আপনার অবস্থান',
    'crop.forMarketPrices': 'বাজার মূল্যের জন্য',
    'crop.locationPlaceholder': 'যেমন পুনে, মহারাষ্ট্র',
    'crop.useCurrentLocation': 'বর্তমান অবস্থান ব্যবহার করুন',
    'crop.geolocationNotSupported': 'জিওলোকেশন সমর্থিত নয়',
    'crop.couldNotGetLocation': 'অবস্থান পাওয়া যায়নি',
    'crop.locationRequired': 'অবস্থান প্রয়োজন',
    'crop.locationRequiredDesc': 'কাছের বাজার খুঁজে পেতে আপনার অবস্থান লিখুন।',
    'crop.nearbyMarkets': 'কাছের বাজার এবং ক্রেতা',
    'crop.findingMarkets': 'আপনার কাছের সেরা বাজার খুঁজছে...',
    'crop.avgPriceShort': 'গড় মূল্য',
    'crop.transport': 'পরিবহন',
    'crop.error': 'ত্রুটি',
    'crop.errorDesc': 'সুপারিশ তৈরি করতে ব্যর্থ। অনুগ্রহ করে আবার চেষ্টা করুন।',
    'crop.marketsUnavailable': 'বাজার উপলব্ধ নয়',
    'crop.couldNotFetchMarkets': 'বাজার পাওয়া যায়নি',
    'cropName.Rice': 'ধান',
    'cropName.Wheat': 'গম',
    'cropName.Corn': 'ভুট্টা',
    'cropName.Barley': 'যব',
    'cropName.Sugarcane': 'আখ',
    'cropName.Cotton': 'তুলা',
    'cropName.Tomato': 'টমেটো',
    'cropName.Potato': 'আলু',
    'crop.months': 'মাস',
    'crop.trendUp': 'বাড়ছে',
    'crop.trendDown': 'কমছে',
    'crop.trendStable': 'স্থিতিশীল',
    'crop.pricesAboveAvg': 'দাম গড়ের উপরে। শীঘ্রই বিক্রি করার কথা ভাবুন।',
    'crop.pricesBelowAvg': 'দাম গড়ের নিচে। শীর্ষ মাসে সংরক্ষণ করে বিক্রি করুন।',
    'crop.pricesStable': 'স্থিতিশীল দাম। সেরা রিটার্নের জন্য শীর্ষ মাসে বিক্রি করুন।',
    'crop.perQuintal': '/কুইন্টাল',
  },
  mr: {
    home: 'मुख्यपृष्ठ',
    recommend: 'पीक शिफारस',
    predict: 'उत्पन्न अंदाज',
    weatherAlerts: 'हवामान',
    schemes: 'योजना',
    tutorials: 'ट्युटोरियल्स',
    about: 'आमच्याबद्दल',
    contact: 'संपर्क',
    title: 'फार्मफ्यूजन 🌱',
    subtitle: 'शेतकऱ्यांना AI सोबत पीक शिफारशी आणि सरकारी योजनांसह मदत.',
    btnRec: 'शिफारस मिळवा',
    btnYield: 'उत्पन्न अंदाज',
    heroTitle: 'फार्मफ्यूजन',
    heroSubtitle: 'शाश्वत शेतीसाठी AI-चालित पीक शिफारशी, उत्पादन अंदाज आणि सरकारी योजनांमध्ये निर्बाध प्रवेशासह शेतकऱ्यांना सक्षम करणे.',
    startJourney: 'तुमचा प्रवास सुरू करा',
    learnMore: 'अधिक जाणून घ्या',
    heroStatFarmers: 'मदत केलेले शेतकरी',
    heroStatCrops: 'पीक प्रकार',
    heroStatAccuracy: 'अचूकता',
    heroStatSchemes: 'शासकीय योजना',
    cropTitle: 'स्मार्ट पीक शिफारस',
    cropSubtitle: 'आपल्या मातीच्या स्थिती आणि पर्यावरणीय घटकांवर आधारित AI-चालित पीक शिफारसी मिळवा.',
    soilEnvData: 'माती आणि पर्यावरण डेटा',
    recommendedCrop: 'शिफारस केलेला पीक',
    optimalForConditions: 'हे पीक आपल्या सध्याच्या माती व पर्यावरणीय परिस्थितींना अनुकूल आहे.',
    yieldTitle: 'बुद्धिमान उत्पन्न अंदाज',
    yieldSubtitle: 'पर्यावरणीय घटक आणि शेती पद्धतींवर आधारित प्रगत AI मॉडेल्सद्वारे आपल्या पिकांचे उत्पादन अंदाज करा.',
    cropEnvData: 'पीक आणि पर्यावरण डेटा',
    predictedYield: 'अंदाजे उत्पन्न',
    accuracyRate: 'अचूकता दर',
    schemesTitle: 'सरकारी योजना आणि सहाय्य',
    schemesSubtitle: 'संपूर्ण भारतातील शेतकऱ्यांना सक्षम करण्यासाठी डिझाइन केलेल्या व्यापक कृषी धोरणे, सबसिडी आणि समर्थन कार्यक्रम एक्सप्लोर करा.',
    keyBenefits: 'मुख्य फायदे',
    applyNow: 'आता अर्ज करा',
    tutorialsTitle: 'सर्वसमावेशक शिक्षण केंद्र',
    tutorialsSubtitle: 'तज्ञ-क्युरेटेड ट्यूटोरियल, संशोधन पेपर्स आणि इंटरॅक्टिव्ह लर्निंग मॉड्यूल्सद्वारे आधुनिक शेती तंत्रांमध्ये प्रभुत्व मिळवा.',
    startLearning: 'शिकायला सुरुवात करा',
    learningPaths: 'संरचित शिकण्याचे मार्ग',
    aboutTitle: 'बद्दल',
    aboutSubtitle: 'आम्ही कृत्रिम बुद्धिमत्तेद्वारे कृषिमध्ये क्रांती घडवून आणण्याच्या मोहिमेवर आहोत, जगभरातील शेतकऱ्यांसाठी शेती अधिक कार्यक्षम, टिकाऊ आणि फायदेशीर बनवत आहोत.',
    whyChoose: 'फार्मफ्यूजन का निवडावे?',
    ourTeam: 'आमची तज्ञ टीम',
    joinRevolution: 'कृषि क्रांतीत सामील व्हा',
    revolutionText: 'शेतीच्या भविष्याचा भाग व्हा. एकत्रितपणे, आम्ही सर्वांसाठी अधिक टिकाऊ आणि समृद्ध कृषी पर्यावरण तयार करत आहोत.',
    contactTitle: 'संपर्कात रहा',
    contactSubtitle: 'प्रश्न आहेत किंवा समर्थन हवे आहे? फार्मफ्यूजनचा जास्तीत जास्त फायदा घेण्यासाठी आम्ही येथे तुम्हाला मदत करण्यासाठी आहोत. वैयक्तिक सहाय्यासाठी आमच्या टीमशी संपर्क साधा.',
    quickMessage: 'त्वरित संदेश',
    yourName: 'तुमचे नाव',
    yourEmail: 'तुमचा ईमेल',
    yourMessage: 'तुमचा संदेश',
    sending: 'पाठवत आहे...',
    sendMessage: 'संदेश पाठवा',
    faq: 'वारंवार विचारले जाणारे प्रश्न',
    growingTogether: 'एकत्र वाढत आहोत',
    thankYou: 'फार्मफ्यूजन समुदायाचा भाग असल्याबद्दल धन्यवाद. एकत्रितपणे, आम्ही कृषिसाठी अधिक स्मार्ट, अधिक टिकाऊ भविष्य तयार करत आहोत.',
    
    pmKisan: 'पीएम-किसान योजना',
    pmKisanDesc: 'लहान आणि सीमांत शेतकऱ्यांना थेट ₹6,000 वार्षिक आर्थिक मदत.',
    pmKisanBenefit1: 'प्रत्यक्ष लाभ हस्तांतरण',
    pmKisanBenefit2: 'कोणतेही मध्यस्थ नाहीत',
    pmKisanBenefit3: 'संपूर्ण भारतात कव्हरेज',
    soilHealth: 'माती आरोग्य कार्ड',
    soilHealthDesc: 'सर्वसमावेशक माती चाचणी आणि पीक-विशिष्ट शिफारसी.',
    soilHealthBenefit1: 'मोफत माती चाचणी',
    soilHealthBenefit2: 'पोषक व्यवस्थापन',
    soilHealthBenefit3: 'उत्पादनात सुधारणा',
    pmFasal: 'पीएम फसल बीमा योजना',
    pmFasalDesc: 'नैसर्गिक आपत्ती आणि उत्पादनाच्या नुकसानीविरुद्ध सर्वसमावेशक पीक विमा.',
    pmFasalBenefit1: 'कमी प्रीमियम दर',
    pmFasalBenefit2: 'जलद दावा निपटान',
    pmFasalBenefit3: 'तंत्रज्ञान एकत्रीकरण',
    kisanCredit: 'किसान क्रेडिट कार्ड',
    kisanCreditDesc: 'शेती खर्च आणि गुंतवणुकीसाठी कमी व्याज कर्ज.',
    kisanCreditBenefit1: 'सोपा अर्ज',
    kisanCreditBenefit2: 'लवचिक परतफेड',
    kisanCreditBenefit3: 'कमी व्याज दर',
    helplineSupport: 'हेल्पलाइन समर्थन',
    helplineDesc: 'अर्ज आणि प्रश्नांसाठी मदत मिळवा',
    digitalServices: 'डिजिटल सेवा',
    digitalServicesDesc: 'सरकारी पोर्टलद्वारे ऑनलाइन सेवा प्रवेश करा',
    documentation: 'दस्तऐवजीकरण',
    documentationDesc: 'आवश्यक दस्तऐवज आणि पात्रता निकष',
    downloadGuidelines: 'मार्गदर्शक तत्त्वे डाउनलोड करा',
    
    modernFarming: 'आधुनिक शेती तंत्रे',
    modernFarmingDesc: 'अचूक शेती, स्मार्ट सिंचन प्रणाली आणि टिकाऊ कृषी पद्धती शिका.',
    cropCultivation: 'पीक लागवड मूलभूत गोष्टी',
    cropCultivationDesc: 'शेतीतील नवशिक्यांसाठी सर्वसमावेशक पायरी-दर-पायरी व्हिडिओ मार्गदर्शक.',
    icarResearch: 'ICAR संशोधन संसाधने',
    icarResearchDesc: 'प्रगत कृषी संशोधन, प्रकाशने आणि तज्ञ मार्गदर्शन प्रवेश करा.',
    ministryGuidelines: 'मंत्रालय मार्गदर्शक तत्त्वे',
    ministryGuidelinesDesc: 'अधिकृत धोरणे, नवीनतम कृषी मार्गदर्शक तत्त्वे आणि सरकारी उपक्रम.',
    videoCourse: 'व्हिडिओ अभ्यासक्रम',
    videoSeries: 'व्हिडिओ मालिका',
    researchPortal: 'संशोधन पोर्टल',
    documentationType: 'दस्तऐवजीकरण',
    selfPaced: 'स्व-गती',
    reference: 'संदर्भ',
    beginner: 'शुरुवातीचा',
    intermediate: 'मध्यम',
    advanced: 'प्रगत',
    allLevels: 'सर्व स्तर',
    beginnerFarmer: 'सुरुवातीचा शेतकरी',
    beginnerDesc: 'तुमचा कृषी प्रवास सुरू करा',
    advancedTechniques: 'प्रगत तंत्रे',
    advancedDesc: 'आधुनिक शेती पद्धती',
    agriBusiness: 'कृषी व्यवसाय',
    agriBusinessDesc: 'व्यावसायिक शेती रणनीती',
    basicFarming: 'मूलभूत शेती',
    soilBasics: 'माती मूलभूत गोष्टी',
    cropSelection: 'पीक निवड',
    precisionFarming: 'अचूक शेती',
    iotAgriculture: 'शेतीमध्ये IoT',
    dataAnalytics: 'डेटा विश्लेषण',
    marketAnalysis: 'बाजार विश्लेषण',
    supplyChain: 'पुरवठा साखळी',
    financialPlanning: 'आर्थिक नियोजन',
    tutorialsCount: 'ट्युटोरियल',
    learnersCount: 'शिकणारे',
    expertsCount: 'तज्ञ',
    rating: 'रेटिंग',
    
    ourMission: 'आमचे ध्येय',
    missionDesc: 'शेती अधिक स्मार्ट, टिकाऊ आणि फायदेशीर बनवण्यासाठी अत्याधुनिक AI तंत्रज्ञानासह शेतकऱ्यांना सक्षम करणे.',
    innovation: 'नवोपक्रम',
    innovationDesc: 'पारंपारिक शेती पद्धती बदलून, क्रांतिकारक AI/ML तंत्रज्ञान थेट शेतात आणणे.',
    community: 'समुदाय',
    communityDesc: 'कृषी तज्ञ, संशोधक आणि आधुनिक संसाधनांसह शेतकऱ्यांना जोडणारे मजबूत नेटवर्क तयार करणे.',
    sustainability: 'टिकाऊपणा',
    sustainabilityDesc: 'पर्यावरण अनुकूल शेती पद्धतींना प्रोत्साहन देणे जे भविष्यातील पिढ्यांसाठी आपल्या पर्यावरणाचे संरक्षण करतात.',
    reliablePredictions: 'विश्वासार्ह अंदाज',
    reliableDesc: 'विशाल कृषी डेटासेटवर प्रशिक्षित AI मॉडेल',
    fastProcessing: 'जलद प्रक्रिया',
    fastDesc: 'त्वरित शिफारसी आणि उत्पादन अंदाज',
    wideCoverage: 'व्यापक कव्हरेज',
    wideDesc: 'एकाधिक प्रदेशात शेतकऱ्यांना समर्थन',
    userSatisfaction: 'वापरकर्ता समाधान',
    satisfactionDesc: 'शेतकरी समुदायाकडून सकारात्मक अभिप्राय',
    aiTeam: 'AI संशोधन टीम',
    aiTeamRole: 'प्रगत अंदाज मॉडेल विकसित करणे',
    aiExpertise: 'मशीन लर्निंग आणि कृषी',
    agriExperts: 'कृषी तज्ञ',
    agriExpertsRole: 'डोमेन ज्ञान प्रदान करणे',
    agriExpertise: 'पीक विज्ञान आणि माती व्यवस्थापन',
    designTeam: 'डिझाइन टीम',
    designTeamRole: 'सहज वापरकर्ता अनुभव तयार करणे',
    designExpertise: 'UX/UI आणि उत्पादन डिझाइन',
    trustedFarmers: '10,000+ शेतकऱ्यांद्वारे विश्वासू',
    uptimeGuarantee: '99.9% अपटाइम हमी',
    
    email: 'ईमेल',
    phone: 'फोन',
    socialMedia: 'सोशल मीडिया',
    supportHours: 'समर्थन वेळा',
    supportHoursDesc: 'सोमवार - शुक्रवार: सकाळी 9:00 - संध्याकाळी 6:00 IST',
    location: 'स्थान',
    locationDesc: 'संपूर्ण भारतात शेतकऱ्यांना सेवा देणे',
    responseTime: 'प्रतिसाद वेळ',
    responseTimeDesc: '2 तासांच्या आत सरासरी प्रतिसाद',
    faqQ1: 'पीक शिफारसी किती अचूक आहेत?',
    faqA1: 'व्यापक चाचणीच्या आधारे आमचे AI मॉडेल 95% अचूकता प्राप्त करतात.',
    faqQ2: 'फार्मफ्यूजन वापरण्यासाठी मोफत आहे का?',
    faqA2: 'होय! सर्व शेतकऱ्यांसाठी मूलभूत वैशिष्ट्ये पूर्णपणे मोफत आहेत.',
    faqQ3: 'तुम्ही कोणत्या भाषांना समर्थन देता?',
    faqA3: 'आम्ही इंग्रजी, हिंदी, तमिळ, बंगाली आणि मराठी समर्थन देतो.',
    faqQ4: 'मला तांत्रिक समर्थन कसे मिळेल?',
    faqA4: 'त्वरित मदतीसाठी फोन किंवा ईमेलद्वारे आमच्याशी संपर्क साधा.',
    nameRequired: 'नाव आवश्यक आहे',
    nameRequiredDesc: 'कृपया तुमचे नाव प्रविष्ट करा',
    invalidEmail: 'अवैध ईमेल',
    invalidEmailDesc: 'कृपया वैध ईमेल पत्ता प्रविष्ट करा',
    messageRequired: 'संदेश आवश्यक आहे',
    messageRequiredDesc: 'कृपया तुमचा संदेश प्रविष्ट करा',
    messageSent: 'संदेश पाठवला! ✅',
    messageSentDesc: 'आम्ही लवकरच तुमच्याशी संपर्क साधू.',
    
    'soilAnalysis.title': 'AI माती विश्लेषण',
    'soilAnalysis.description': 'त्वरित विश्लेषणासाठी तुमच्या मातीचा फोटो घ्या किंवा प्रतिमा अपलोड करा',
    'soilAnalysis.camera': 'कॅमेरा वापरा',
    'soilAnalysis.capture': 'फोटो घ्या',
    'soilAnalysis.upload': 'प्रतिमा अपलोड करा',
    'soilAnalysis.getWeather': 'स्थानावरून हवामान डेटा मिळवा',
    'soilAnalysis.success': 'विश्लेषण पूर्ण!',
    'soilAnalysis.successDesc': 'माती डेटाचे विश्लेषण केले गेले आहे आणि फॉर्ममध्ये भरले गेले आहे.',
    'soilAnalysis.error': 'विश्लेषण अयशस्वी',
    'soilAnalysis.cameraError': 'कॅमेरा त्रुटी',
    'soilAnalysis.cameraErrorDesc': 'कॅमेरा प्रवेश करू शकला नाही',
    'soilAnalysis.results': 'विश्लेषण परिणाम',
    'soilAnalysis.soilType': 'माती प्रकार',
    'soilAnalysis.moisture': 'आर्द्रता',
    'soilAnalysis.health': 'आरोग्य',
    'soilAnalysis.recommendations': 'शिफारसी',
    'weather.success': 'हवामान डेटा पुनर्प्राप्त केला!',
    'weather.successDesc': 'पर्यावरणीय डेटा फॉर्ममध्ये भरला गेला आहे.',
    'weather.error': 'स्थान त्रुटी',
    'weather.errorDesc': 'तुमचे स्थान मिळवू शकले नाही',

    // Weather Alerts Section
    'weatherAlerts.title': 'हवामान आणि स्मार्ट लागवड मार्गदर्शक',
    'weatherAlerts.subtitle': 'AI-चालित इष्टतम लागवड वेळ सूचनांसह 7-दिवसांचा अंदाज',
    'weatherAlerts.currentWeather': 'सध्याचे हवामान',
    'weatherAlerts.cropProtection': 'पीक संरक्षण सूचना',
    'weatherAlerts.temperature': 'तापमान',
    'weatherAlerts.humidity': 'आर्द्रता',
    'weatherAlerts.rainfall': 'पाऊस (आज)',
    'weatherAlerts.forecast': '7-दिवसांचा हवामान अंदाज',
    'weatherAlerts.plantingSuggestions': 'इष्टतम लागवड सूचना',
    'weatherAlerts.avgHigh': 'सरासरी उच्च',
    'weatherAlerts.avgLow': 'सरासरी निम्न',
    'weatherAlerts.totalRain': 'एकूण पाऊस',
    'weatherAlerts.rainChance': 'पावसाची शक्यता',
    'weatherAlerts.bestDays': 'या आठवड्यात लागवडीसाठी सर्वोत्तम दिवस',
    'weatherAlerts.irrigationSchedule': 'स्मार्ट सिंचन वेळापत्रक',
    'weatherAlerts.dailySchedule': 'दैनिक सिंचन वेळापत्रक',
    'weatherAlerts.weeklyNeeds': 'साप्ताहिक पाण्याची आवश्यकता',
    'weatherAlerts.soilMoisture': 'माती आर्द्रता अंदाज',
    'weatherAlerts.irrigationTips': 'सिंचन सूचना',
    'weatherAlerts.loading': 'हवामान डेटा लोड होत आहे...',
    'weatherAlerts.clickRefresh': 'हवामान डेटा लोड करण्यासाठी रिफ्रेश क्लिक करा',
    'weatherAlerts.weatherUpdated': 'हवामान अपडेट झाले!',
    'weatherAlerts.highTemp': 'उच्च तापमान सूचना! सिंचन विचारात घ्या आणि पिकांना सावली द्या.',
    'weatherAlerts.lowTemp': 'कमी तापमान चेतावनी! पिकांचे दंवापासून संरक्षण करा.',
    'weatherAlerts.highHumidity': 'उच्च आर्द्रता आढळली! बुरशीजन्य रोगांचा धोका.',
    'weatherAlerts.heavyRain': 'जोरदार पाऊस अपेक्षित! योग्य निचरा सुनिश्चित करा.',
    'weatherAlerts.dryConditions': 'कोरड्या परिस्थिती! सिंचन नियोजन करा.',
    'weatherAlerts.favorable': 'हवामान परिस्थिती शेतीसाठी अनुकूल आहे.',

    // Yield Prediction Section
    'yield.calculating': 'उत्पन्नाची गणना होत आहे...',
    'yield.dataAutoFilled': 'डेटा स्वयंचलितपणे भरला गेला!',
    'yield.dataAutoFilledDesc': 'पीक डेटा लोड झाला. कृपया कीटकनाशक आणि क्षेत्र जोडा.',
    'yield.missingInfo': 'माहिती अपूर्ण आहे',
    'yield.fillAllFields': 'कृपया सर्व आवश्यक फील्ड भरा.',
    'yield.predictionReady': 'उत्पन्न अंदाज तयार!',
    'yield.expectedYield': 'अपेक्षित उत्पन्न',
    'yield.error': 'उत्पन्न अंदाज अयशस्वी. कृपया पुन्हा प्रयत्न करा.',
    'yield.cropName': 'पिकाचे नाव',
    'yield.year': 'वर्ष',
    'yield.rainfall': 'पाऊस',
    'yield.pesticide': 'कीटकनाशक वापर',
    'yield.temperature': 'तापमान',
    'yield.area': 'क्षेत्र',
    'yield.viewHistory': 'इतिहास पहा',
    'yield.hideHistory': 'इतिहास लपवा',
    'yield.recentPredictions': 'अलीकडील अंदाज',
    'yield.deleted': 'हटवले',
    'yield.removedFromHistory': 'अंदाज इतिहासातून काढला',
    'yield.weatherImpact': 'हवामान प्रभाव',
    'yield.weatherImpactDesc': 'पावसाचे नमुने वाढ चक्रावर परिणाम करतात',
    'yield.tempImpact': 'तापमान',
    'yield.tempImpactDesc': 'इष्टतम तापमान उत्पन्न वाढवते',
    'yield.pesticideImpact': 'कीटकनाशक वापर',
    'yield.pesticideImpactDesc': 'योग्य कीड नियंत्रण उत्पादन वाढवते',
    'yield.areaEfficiency': 'क्षेत्र कार्यक्षमता',
    'yield.areaEfficiencyDesc': 'जमीन वापर ऑप्टिमायझेशन',
    'yield.aiRecommendations': 'AI-चालित शिफारसी',

    // Crop Recommendation Section
    'crop.analyzingSoil': 'मातीचे विश्लेषण होत आहे...',
    'crop.recommendationGenerated': 'शिफारस तयार!',
    'crop.basedOnSoil': 'आपल्या मातीच्या स्थितीनुसार, आम्ही शिफारस करतो',
    'crop.growthDuration': 'वाढ कालावधी',
    'crop.approximately': 'अंदाजे',
    'crop.days': 'दिवस',
    'crop.useForYield': 'उत्पन्न अंदाजासाठी वापरा',
    'crop.marketInsights': 'बाजार किंमत अंतर्दृष्टी',
    'crop.currentPrice': 'सध्याची किंमत',
    'crop.avgPrice': 'सरासरी किंमत (12 महिने)',
    'crop.bestSellTime': 'विक्रीसाठी सर्वोत्तम वेळ',
    'crop.priceHistory': '12-महिने किंमत कल',
    'crop.recommendation': 'शिफारस',
    'crop.soilAnalysis': 'माती विश्लेषण',
    'crop.soilAnalysisDesc': 'NPK पातळी पोषक तत्वांची उपलब्धता ठरवतात',
    'crop.climateFactors': 'हवामान घटक',
    'crop.climateFactorsDesc': 'तापमान आणि आर्द्रता वाढीवर परिणाम करतात',
    'crop.waterManagement': 'जल व्यवस्थापन',
    'crop.waterManagementDesc': 'पावसाचे नमुने सिंचन आवश्यकता मार्गदर्शन करतात',
    'crop.phBalance': 'pH संतुलन',
    'crop.phBalanceDesc': 'इष्टतम pH पोषक तत्व शोषण सुनिश्चित करते',
    'crop.nitrogen': 'नायट्रोजन (N)',
    'crop.phosphorus': 'फॉस्फरस (P)',
    'crop.potassium': 'पोटॅशियम (K)',
    'crop.humidity': 'आर्द्रता',
    'crop.phValue': 'pH मूल्य',

    // Chatbot
    'chatbot.title': 'आदिई - शेती सहाय्यक',
    'chatbot.placeholder': 'आदिईला शेतीबद्दल विचारा...',
    'chatbot.listening': 'ऐकत आहे...',
    'chatbot.speakNow': 'आता बोला',
    'chatbot.greeting': 'नमस्कार! मी आदिई',
    'chatbot.askAnything': 'शेतीबद्दल काहीही विचारा!',
    'chatbot.topics': 'पिके • हवामान • कीड • माती • तंत्रे',
    'chatbot.voiceSupport': '5 भाषांमध्ये बोला किंवा टाइप करा',
    'chatbot.language': 'भाषा',
    'chatbot.stop': 'थांबा',
    'nav.login': 'लॉगिन',
    'nav.logout': 'लॉगआउट',
    'nav.loginSignup': 'लॉगिन / साइन अप',
    'nav.welcome': 'स्वागत',
    'nav.hello': 'नमस्कार',
    'crop.yourLocation': 'तुमचे स्थान',
    'crop.forMarketPrices': 'बाजार किंमतींसाठी',
    'crop.locationPlaceholder': 'उदा. पुणे, महाराष्ट्र',
    'crop.useCurrentLocation': 'सध्याचे स्थान वापरा',
    'crop.geolocationNotSupported': 'जिओलोकेशन समर्थित नाही',
    'crop.couldNotGetLocation': 'स्थान मिळवता आले नाही',
    'crop.locationRequired': 'स्थान आवश्यक आहे',
    'crop.locationRequiredDesc': 'कृपया जवळचे बाजार शोधण्यासाठी तुमचे स्थान प्रविष्ट करा.',
    'crop.nearbyMarkets': 'जवळचे बाजार आणि खरेदीदार',
    'crop.findingMarkets': 'तुमच्या जवळचे सर्वोत्तम बाजार शोधत आहे...',
    'crop.avgPriceShort': 'सरासरी किंमत',
    'crop.transport': 'वाहतूक',
    'crop.error': 'त्रुटी',
    'crop.errorDesc': 'शिफारस तयार करता आली नाही. कृपया पुन्हा प्रयत्न करा.',
    'crop.marketsUnavailable': 'बाजार उपलब्ध नाहीत',
    'crop.couldNotFetchMarkets': 'बाजार मिळवता आले नाहीत',
    'cropName.Rice': 'तांदूळ',
    'cropName.Wheat': 'गहू',
    'cropName.Corn': 'मका',
    'cropName.Barley': 'जव',
    'cropName.Sugarcane': 'ऊस',
    'cropName.Cotton': 'कापूस',
    'cropName.Tomato': 'टोमॅटो',
    'cropName.Potato': 'बटाटा',
    'crop.months': 'महिने',
    'crop.trendUp': 'वाढत आहे',
    'crop.trendDown': 'कमी होत आहे',
    'crop.trendStable': 'स्थिर',
    'crop.pricesAboveAvg': 'किमती सरासरीपेक्षा जास्त आहेत. लवकर विक्री करण्याचा विचार करा.',
    'crop.pricesBelowAvg': 'किमती सरासरीपेक्षा कमी आहेत. शिखर महिन्यांमध्ये साठवून विकणे उत्तम.',
    'crop.pricesStable': 'स्थिर किमती. सर्वोत्तम परताव्यासाठी शिखर महिन्यांमध्ये विका.',
    'crop.perQuintal': '/क्विंटल',
  }
};

export type LanguageContextType = {
  currentLang: string;
  changeLanguage: (lang: string) => void;
  t: (key: string) => string;
  availableLanguages: string[];
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [currentLang, setCurrentLang] = useState<string>('en');

  useEffect(() => {
    const savedLang = localStorage.getItem('farmfusion-language');
    if (savedLang && translations[savedLang]) {
      setCurrentLang(savedLang);
    }
  }, []);

  const changeLanguage = (lang: string) => {
    if (translations[lang]) {
      setCurrentLang(lang);
      localStorage.setItem('farmfusion-language', lang);
    }
  };

  const t = (key: string): string => {
    return translations[currentLang]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider
      value={{ currentLang, changeLanguage, t, availableLanguages: Object.keys(translations) }}
    >
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) {
    const fallbackLang = (typeof window !== 'undefined' && localStorage.getItem('farmfusion-language')) || 'en';
    const t = (key: string): string => {
      return translations[fallbackLang]?.[key] || translations.en[key] || key;
    };
    return {
      currentLang: fallbackLang,
      changeLanguage: (_: string) => {
        console.warn('useLanguage called outside of LanguageProvider');
      },
      t,
      availableLanguages: Object.keys(translations),
    };
  }
  return ctx;
};

export default useLanguage;